### ISSUE TITLE
jsdoc @deprecated is not discoverable when compiled with the removeComments flag

### ISSUE THREAD

**Issue by dnalborczyk** [apollographql/federation#1025]
because of this [issue](https://github.com/microsoft/TypeScript/issues/14619) any jsdoc @ deprecated tags are not discoverable by users. e.g. this one: https://github.com/apollographql/federation/blob/71e0dd1e2e15bcac7919b1253ed231bce009349b/federation-js/src/service/buildSubgraphSchema.ts#L137

depending on the timeline of the removal, some possible solutions:
- remove the flag to strip out comments
- in the above typescript issue is a workaround mentioned, essentially compiling twice: once for javascript, once for the ambient types. I don't think it's worth the trouble.
- one could (search and) inject the @ deprecated tag after the build into the ambient files.
- do nothing, leave as is - might be removed soon anyways

or better, one could also use the node.js wrapper function [util.deprecate()](https://nodejs.org/api/util.html#util_util_deprecate_fn_msg_code) which essentially writes a `deprecated` message [once for the lifetime of the application] to the console. doing so would notify javascript and typescript users regardless of what IDE has been used.

I can also provide a PR with the suggested wrapper.

**Comment by trevor-scheer** [comment]
Thanks @dnalborczyk, I like the last suggestion and TIL. Since these warnings are natively suppressible I'd certainly entertain a PR which implements this 👍
