### ISSUE TITLE
__resolveReference within the same service

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/federation#1055]
Hi. I have been using Apollo Federation and while __resolveReference has worked great for resolving data between microservices, what do we do if we want to use __resolveReference within the same service? 

Say there are 3 or 4 types in the same GraphQL service and I want to return ID and use __resolveReference within the same service. I have noticed that it only works when used in some other service.

Any thoughts? Thanks.

**Comment by HunderlineK** [comment]
@glasser I think the apollo project was appropriate for this issue, as it is supporting a feature that federation provides within the same subgraph, which might not even be part of a federation.

**Comment by glasser** [comment]
When the issue was opened, the relevant code was part of the `apollo-server` repo, but it now lives in the `federation` repo.

**Comment by HunderlineK** [comment]
@glasser Sure, but still this counts as a feature request for `apollo-server`. Implementing it would be and should completely independent from the code in the federation repo. Would you like me to create a separate feature request issue?

**Comment by angelo-moreira** [comment]
Thank you very much for your reply @queerviolet I have tried to look through the source code and tests to try to understand what you meant with this:

> but this would require hooking execution more deeply than we currently do.

But unfortunately I am not familiar enough with the codebase, would you please give me any clues about how to even start to tackle this?

Thank you in advance.
