### ISSUE TITLE
Confusing error messages for mismatched value type interfaces

### ISSUE THREAD

**Issue by brainkim** [apollographql/federation#1074]
humans.graphql
```gql
interface Character {
  id: ID!
  name: String!
  friends: [Character]
}

type Human implements Character {
  id: ID!
  name: String!
  friends: [Character]
  health: Float!
}


type Query {
  human(id: ID!): Human
}
```

droids.graphql
```gql
interface Character {
  id: ID!
  name: String!
  friends: [Character]
  alignment: String!
}

type Droid implements Character {
  id: ID!
  name: String!
  friends: [Character]
  primaryFunction: String
  alignment: String!
}

type Query {
  droid(id: ID!): Droid
}
```

Composing the following subgraphs produces the following errors:

```
There can be only one type named "Character".
Field "Character.id" can only be defined once.
Field "Character.name" can only be defined once.
Field "Character.friends" can only be defined once.
```

The expected errors should be something to do with interface value types not matching between the two subgraphs, i.e. one of these messages (https://www.apollographql.com/docs/federation/errors/#value-types).

Workbench:
```
{"graphName":"interface-value-types","operations":{},"queryPlans":{},"schemas":{"droids":{"shouldMock":true,"sdl":"interface Character {\n  id: ID!\n  name: String!\n  friends: [Character]\n  alignment: String!\n}\n\ntype Droid implements Character {\n  id: ID!\n  name: String!\n  friends: [Character]\n  primaryFunction: String\n  alignment: String!\n}\n\ntype Query {\n  droid(id: ID!): Droid\n}\n","autoUpdateSchemaFromUrl":false},"humans":{"shouldMock":true,"sdl":"interface Character {\n  id: ID!\n  name: String!\n  friends: [Character]\n}\n\ntype Human implements Character {\n  id: ID!\n  name: String!\n  friends: [Character]\n  health: Float!\n}\n\n\ntype Query {\n  human(id: ID!): Human\n}\n","autoUpdateSchemaFromUrl":false}},"supergraphSdl":""}
```

**Comment by pcmanus** [comment]
Fwiw, the upcoming version 2.0 of federation (currently in alpha) now produce the following composition error on this example:
```
Interface field "Character.alignment" is declared in subgraph "droids" but type "Human", which implements "Character" only in subgraph "humans" does not have field "alignment".

droids:5:3
4 |   friends: [Character]
5 |   alignment: String!
  |   ^
6 | }

humans:7:1
6 |
7 | type Human implements Character {
  | ^
8 |   id: ID!
```

I'll note that it doesn't complain that `Character.alignment` is only in the `droids` subgraph because that's something federation 2.0 lets you do in other situations, but it does complain that once composed the `Human` type doesn't have that field but it should.

Does that error make sense?

Of course, this doesn't change the fact the message is confusing on the currently released version of federation (but to manage expectations, most development focus will probably be on the upcoming federation 2.0 version outside of serious bugs).

**Comment by brainkim** [comment]
@pcmanus That makes me wonder if allowing interface value types to define a different set of fields across different subgraphs is that useful. I would expect to only have to care about the interface fields defined my specific subgraph.

If the issue is fixed in Federation 2, then feel free to close! This was from a support ticket.

**Comment by pcmanus** [comment]
> That makes me wonder if allowing interface value types to define a different set of fields is that useful. I would expect to only have to care about the interface fields defined by my specific subgraph when implementing interfaces.

The typical example where an interface wouldn't have the same set of fields in 2 subgraphs is where a subgraph "extends" an interface and its implementations. In the example of this ticket however, it's doing something a bit different where each subgraph provides a different set of "implementations" for the interface, and in that case it is true that they should all more or less be the same (but that feels fairly reasonable).
