### ISSUE TITLE
Schema object is omitted when printed

### ISSUE THREAD

**Issue by sMorm** [apollographql/federation#1094]
# Relevant Packages
`@apollo/federation` v0.33.3
`@apollo/subgraph` 0.1.2

To support the `@contact` directive, a `schema` element must be defined. When building a schema using `buildSubgraphSchema` and printing it via `printSubgraphSchema` the [schema element is stripped](https://github.com/apollographql/federation/blob/main/subgraph-js/src/printSubgraphSchema.ts#L107) without any directives applied.

# Example Code
```javascript
const { gql } = require("apollo-server");
const { buildSubgraphSchema } = require("@apollo/federation");
const { printSubgraphSchema } = require("@apollo/subgraph");
const typeDefs = gql`
  directive @contact(
    name: String!
    url: String!
    description: String!
  ) on SCHEMA

  extend type Query {
    hello: String
  }

  schema @contact(name: "hi", url: "https://hi.com", description: "hi") {
    query: Query
  }
`;

const schemaString = printSubgraphSchema(buildSubgraphSchema({ typeDefs }));
console.log(schemaString);
```

# Expected Behavior
The expected value of `schemaString`.
```graphql
directive @contact(name: String!, url: String!, description: String!) on SCHEMA

extend type Query {
  _service: _Service!
  hello: String
}

schema @contact(name: "hi", url: "https://hi.com", description: "hi") {
  query: Query
}
```

# Actual Behavior
```graphql
directive @contact(name: String!, url: String!, description: String!) on SCHEMA

extend type Query {
  _service: _Service!
  hello: String
}
```

**Comment by cpeacock** [comment]
Hi there!  I'm closing this issue because I believe with Trevor's fixes, these have been addressed in the older stable versions of the gateway.  Please reopen if there's still something amiss.
