### ISSUE TITLE
Installation of `@apollo/gateway` cannot resolve a version of `@apollo/subgraph`

### ISSUE THREAD

**Issue by jonahallibone** [apollographql/federation#1124]
When installing `@apollo/gateway` as described [here](https://www.apollographql.com/docs/federation/gateway/)

 the following error is returned from `npm`:

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @apollo/subgraph@^0.1.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-11-02T19_33_41_237Z-debug.log
```

I have attempted on multiple machines to ensure it's not a cache issue or otherwise

**Comment by trevor-scheer** [comment]
On it, thanks for reporting!

**Comment by trevor-scheer** [comment]
@jonahallibone this should be resolved now. It's possible your `package-lock.json` may be in a bad state after that install. I've only moved the `latest` dist tag to the previously published version for the `@apollo/gateway` (and `@apollo/federation`) packages. You should be able to delete entries from your lockfile related to gateway, federation, and subgraph to resolve the issue if it persists.

Please let me know if this isn't resolved for you!

**Comment by jonahallibone** [comment]
@trevor-scheer thanks seems to be working now!
