### ISSUE TITLE
fix(subgraph): Preserve `resolveReference` fns during schema transforms

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#1131]
Currently `resolveReference` and `resolveObject` are special properties on `GraphQLObjectType`s which don't obey the type system / public API. We should investigate moving these properties to the `extensions` object so they are preserved through normal usage of the public API (i.e. calling `toConfig()` on the object.

Ref: https://github.com/ardatan/graphql-tools/issues/2687

**Comment by glasser** [comment]
@martijnwalraven pointed out in https://github.com/ardatan/graphql-tools/pull/2857#issuecomment-827331698 that this would be a backwards-incompatible change, but I suspect it is fine to make it (and bump the 0.x version).  If for some reason that's not ok, we could put the fields on both places and just document the old way as deprecated and not preserved by things like mapSchema.

We should consider taking the advice on the doc comment on graphql-js `GraphQLObjectTypeExtensions` and put these functions not directly on `extensions` but on an object like `extensions.apolloSubgraph`, for later extensibility.

**Comment by trevor-scheer** [comment]
I haven't validated the workaround myself, but I figure it's worth sharing if anyone finds themselves running into this issue - could be worth a shot.

https://community.apollographql.com/t/are-object-resolvers-broken-with-custom-schema-directives/1578/3

Thanks to @vad3x for providing it.

**Comment by vad3x** [comment]
Hi @trevor-scheer, any updates?

**Comment by trevor-scheer** [comment]
@vad3x no update yet. This is one of those things I'd love to get to, but no idea when. Open to assisting with a PR though!
