### ISSUE TITLE
fix(subgraph): Remove dependency on `apollo-graphql`

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#1134]
`apollo-graphql` is an oddball dependency that exists in the to-be-sunsetted `apollo-tooling` repo. It's the only real cross-dependency of its kind among the federation packages which seems to imply these tools might be better suited within the federation monorepo.

Furthermore, a cross-dependency between the two monorepos (specifically the `apollo-graphql` and the `@apollo/federation` packages) is causing a blocking hiccup which prevents the `apollo-graphql` package from being bumped to the next major (`0.10.x`) due to the current version of `@apollo/federation` requiring `^0.9.x`. We could probably take steps to band-aid this instead but at this point I find it's been a thorn long enough and would rather relocate or remove the dependency altogether.

**Comment by glasser** [comment]
We should also remove it as a dependency of `apollo-server`. Right now it is only used for the various "signature" functions in usage reporting and the op reg, which could easily be inlined into those two separate packages.

**Comment by glasser** [comment]
(While we're at it we can replace printWithReducedWhitespace with graphql-js' own stripIgnoredCharacters.)
