### ISSUE TITLE
Error: Cannot find module 'graphql/validation/rules/UniqueTypeNames

### ISSUE THREAD

**Issue by ruslan-byondxr** [apollographql/federation#1175]
Getting this error while running a minimal example from the Apollo federation getting started tutorial:
https://www.apollographql.com/docs/federation/quickstart/

```
import { ApolloServer } from 'apollo-server';
import { ApolloGateway } from '@apollo/gateway';

const supergraphSdl = ''; // TODO!

const gateway = new ApolloGateway({
  supergraphSdl
});

const server = new ApolloServer({
  gateway,
});

server.listen().then(({ url }) => {
  console.log(`🚀 Gateway ready at ${url}`);
}).catch(err => {console.error(err)});

```

Seems like rules.ts in @apollo/federqtion is failing while importing UniqueTypeNames
https://github.com/apollographql/federation/blob/main/federation-js/src/composition/rules.ts

The latest version of graphql doesn't have this rule. 
Probably they changed it to `UniqueTypeNamesRule.ts`
https://github.com/graphql/graphql-js/tree/main/src/validation/rules

**Comment by ruslan-byondxr** [comment]
https://github.com/graphql/graphql-js/pull/2413

**Comment by persocon** [comment]
lock your graphql version like this
```
"graphql": "15.5.3"
```
:/ until they update and do this #1199

**Comment by trevor-scheer** [comment]
Sorry about the trouble! A few things here:

We're breaking the public contract with those deep imports, but v15+ now publicly supports them (so we can make the switch a non-breaking change!).

Also our docs don't "pin" a major version which means anyone coming along (like yourself) and installing graphql will now get v16, which we don't technically support just yet. I've brought this up to the docs team - to prevent this we should include major versions in our copy/paste install scripts like so `npm install grapqhl@15`.

Side note: you should be getting peer dependency warnings when you `npm install` which let you know this is the case. Those are legit! Don't ignore 😄

Lastly, @persocon is right. You should be able to specifically install `graphql@15` for the time being and you'll be off to the races.

In any case, I've got PRs open to fix specifically this issue as well as to start supporting `graphql@16` altogether, so should have this fixed up soon.

**Comment by trevor-scheer** [comment]
@xelaz this is fixed in federation, I think you're looking for the [tooling repo](https://github.com/apollographql/apollo-tooling).
