### ISSUE TITLE
Add a mechanism to force query-planner choices (tentatively `@override`)

### ISSUE THREAD

**Issue by pcmanus** [apollographql/federation#1177]
As federation 2 adds more flexibility as to what can be composed, it also create more opportunities where the query planner might have to make choices before multiple valid options (though please also see #1176, which is about improving the UX around ensuring such options are only created intentionally).

When faced with options, it is the main role of the query planner to find the most performant one (which may vary depending on the exact details of the query) and the general recommandation is to let the query planner do its job.

There is cases however, the main one being the migration of entity type field between subgraphs, where the created choices are temporary and it is desirable to force the hand of the query-planner (typically, to ensure it use the "new" field declaration as soon as it is exposed, even if the "old" one is not removed yet).

For this, the idea is to allow a new `@override` directive (tentative name) on fields whose effect would essentially be to require that the query planner always favour a field declaration with that `@override` directive.

The exact details of the mechanism still need to be flushed out, and that is one of goal of this issue.

I'll clarify that there exists many ways in which the query planner could be improved, and many ways in which better control of it could be exposed, but this is issue is not meant as an umbrella for such discussions/idea, but rather a focused issue on the particular question of allowing more predictable field migration (though the added mechanism might prove useful in a few other cases).

**Comment by prasek** [comment]
The primary use case we've heard for `@override` is type/field migration across subgraphs, so we're leaning towards using `@moving(to: "subgraph")` instead.

Previously with `@override` you'd have put `@override` on the subgraph that should receive all traffic for that field. This would be done by the subgraph team when they were ready to accept the traffic for that field.

`@moving(to: "subgraph")` would be placed on the existing/old subgraphs to send traffic to a different subgraph if it exists.
> When the `@moving` directive exists on a field of a subgraph, the query planner will resolve the field to that subgraph if and only if the field is not provided on the subgraph the field is moving to. Once the field is present in the destination subgraph, future query plans will resolve to the new subgraph. The destination subgraph would be a required parameter in the directive, and that once the field is available in the destination subgraph, 100% of uncached query plans will resolve to the new subgraph.

To move a field:
1. Mark T.f in "old" with @moving(to: "new")
2. Add T.f in "new"
3. Remove T.f from "old" completely

Would love feedback on:
- use of `@moving(to: "subgraph") approach
- use case details you can offer where this would work well or might encounter issues

**Comment by carldunham** [comment]
I think the issue with that is that it requires the legacy subgraph to get involved, and to have intimate knowledge of the supergraph structure. Ideally, migrating from a monolith to subgraphs would allow the monolith to remain (ignorantly unaware) as a catch-all for the unmigrated parts.

Would much prefer that the mew subgraph be able to say "hey, I'm taking over this type/field, ignore what old cranky legacy has to say about it." This will also allow us to run legacy and subgraphs in parallel, to test, roll back, etc.

**Comment by t-botz** [comment]
I recently went through a field migration and here's my feedback.
I think the migration process should not require modification of the legacy schema because, the reason you are migrating might be:
 1. It doesn't support feature you want, like custom directives
 2. It's a nightmare to change
 3. You don't own it

You could adress that by having `@moving(from:"legacy)` as an option.
I am not to fuss about wording but I dont really like the `@moving, I feel like it's too overloaded.

Let me bounce few ideas

Alternative proposal #1: `@queryplanner(priority:HIGH|MEDIUM|LOW)`
I don't like my wording either but the idea is to tell the query planner the priority of the field. By default everyone is MEDIUM. If you set to HIGH and there is an other service with this field, yours is taking priority.

Alternative proposal #2: `@queryplanner(distribution:75)`
Means sends 75% of the request. Thats one of the feature I wish we had because we wanted to have a way to slowly roll the migrated field. `@queryplanner(distribution:100)` means migrate fully. `@queryplanner(distribution:0)` means send to the service only if no other alternatives.

**Comment by mmartinson** [comment]
Agree that it would be preferable to avoid `@Moving` directives, so older services can remain agnostic if not amenable to change.

A distribution directive would be highly valuable for cases I'm looking at of migrating a high traffic production load via incremental traffic shifting to avoid risk. Higher granularity of control compared to low/medium/high would be helpful. 

The interactions between distributions tags on the same field wouldn't be entirely intuitive. Some initial thoughts:

1) Distribution defaults to 0, allowing the legacy provider to be migrated fully away from without being changed.
2) Weights are relative. Two services with distributions of 50/150 would be routed at 25/75%. This reduces schema composition friction.
3) Any distribution less than 100 that is not explicitly claimed is routed to existing `distribution:0` providers. This is how we'd get incremental traffic shifting away from a legacy service that can't be changed. For example, with a newer implementation tagged as `distribution:10`, it would get 10% and the legacy untagged implementation the other 90%. Once the new is at 100+, legacy receives no traffic.

In addition to schema-based routing controls, having a scriptable override at the gateway/router level would be super valuable traffic shifting hotfixes.

**Comment by pcmanus** [comment]
Some updates on this.

Short term (that is, hopefully for 2.0 GA), our plan is to support an `@override(from: "subgraph-name")` directive. So compared to the `@moving(to:)` initially mentioned:
1. this is essentially a `@moving(from:)`, because we agree that modifying the old subgraph is not always convenient/desirable.
2. we also agree "moving" might not be such a great name after all, and we feel `@override` is decent.

That said, I do hear the comments here about some fine-grained traffic control. And this is absolutely something I want to look at eventually, but this is somewhat more involved than the `@override` we're discussing here and might take a bit more time. In particular, while I 100% agree some traffic control would be great, I'm still a bit unsure on whether composition is the right place for it, because composition is somewhat static while I think traffic control may need to be more dynamic.

**Comment by clenfest** [comment]
Code is in and merged as https://github.com/apollographql/federation/pull/1484.
