### ISSUE TITLE
Selectively hiding subgraph elements from the supergraph API (`@inaccessible`)

### ISSUE THREAD

**Issue by pcmanus** [apollographql/federation#1178]
Currently, all types and their elements in subgraphs are exposed in the composed supergraph API. It would however be useful to be able to mark some of those elements (fields, enum values, full types, ...?) as `@inacessible`, which would prevent those elements from being exposed in the supergraph API.

Two main use case come first in mind:
1. @key/@requires fields that are used internally to "route" queries between subgraphs, but that one may not want to expose externally. 
2. schema evolution: when evolving a schema, it might be useful to be able to push some changes to subgraph piecemeal, but without exposing the new elements until the migration to all subgraphs is complete.

The gateway code already handles an `@inaccessible` "internally" in its supergraph artifact for related purposes. This ticket is about exposing that directive in subgraphs.

**Comment by craig-day** [comment]
I would love to see this! This could help better support interfaces in federated graphs. 


<details>
<summary>
Expand this section for a specific example I have (using federation 2).
</summary>

**Desired schema**

```graphql
type Article {
  id: ID!
  title: String!
  author: User!
}
```

However, in my case, `User` is a interface so it can't directly become an entity. This isn't necessarily a problem, but it makes resolution more interesting. Following the [Separation of concerns](https://www.apollographql.com/docs/federation/v2/#separation-of-concerns) advice, it seems like the best thing to do would be to define the `Article` type in each subgraph and have them provide the fields they can resolve. So, my subgraphs could look like this:

**Subgraph A**

```graphql
type Article @key(fields: "id") {
  id: ID! @shareable
  title: String!
}
```

**Subgraph B**

```graphql
type Article @key(fields: "id") {
  id: ID! @shareable
  author: User!
}

interface User {
  id: ID!
  name: String!
}

type Author implements User {
  id: ID!
  name: String!
  # ... other fields
}
```

So far, so good. The problem however comes when **Subgraph B** goes to resolve the author. As currently written, the only reference passed into the subgraph resolution query would be the `id` of the article. However, we need a property like `authorId` to avoid having to re-fetch the article in **Subgraph B** just to learn the author's ID. So, we could easily add that field and make it part of the key.

```graphql
type Article @key(fields: "id") @key(fields: "id authorId") {
  id: ID! @shareable
  authorId: ID!
}
```

however, the supergraph would then end up exposing `authorId` and `author` on `Article`. This is not ideal, we only want `author`. It would be perfect to add `@inaccessible` to the `authorId` field, so it can be used during resolution, but is not
present in the supergraph schema!

Sorry for the long-winded answer, but this feature solves a ton of problems for us and I'd love to see it.
</details>

**Comment by cpeacock** [comment]
Committed to the `2.0.0-preview.8` release.

**Comment by cpeacock** [comment]
One further clarification, this is for use in subgraphs on the types and fields `@inaccessible` is currently available for.  Enums, inputs, and others will be coming across in a subsequent release.
