### ISSUE TITLE
router-bridge: only trigger rebuilds on changes of the js source, not always

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#1192]
Currently the `router-bridge` package needs to be rebuilt on every Rust build because the `target` directory is included in its `build.ts` change detection `rebuild-if`s.  We should rebuild only on the JS file change, since otherwise things work naturally.

**Comment by abernix** [comment]
I think this is fixed by https://github.com/apollographql/federation/pull/1188, but please re-open if it is not, @o0Ignition0o! 😄

**Comment by o0Ignition0o** [comment]
https://github.com/apollographql/federation/pull/1211 is going one step further, but the issue can be closed indeed!
