### ISSUE TITLE
chore(deps): Support graphql@16

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#1199]
Like it says in the title, add support for `graphql@16`!  🎉  (v0.x and v2)

**Comment by trevor-scheer** [comment]
Related: https://github.com/apollographql/federation/pull/1207

**Comment by setchy** [comment]
yes please 🙏

**Comment by m1heng** [comment]
Do we have any progress in this 🥺

**Comment by m1heng** [comment]
@trevor-scheer I think your #1129 has solved this in main right?

**Comment by trevor-scheer** [comment]
@m1heng yes it's finished on main. @clenfest is working on backporting the changes to the 0.x branch as well.

**Comment by m1heng** [comment]
Cool, I will close my PR then. Wish to see the release from 0.x soon.
