### ISSUE TITLE
Add @defer / @stream support

### ISSUE THREAD

**Issue by hwillson** [apollographql/federation#1204]
This is the main feature request tracking issue for adding @defer / @stream support to the Apollo Gateway. More details will be broken out shortly (related Apollo Server issue: https://github.com/apollographql/apollo-server/issues/5893).

**Comment by bhwanip** [comment]
Need @defer support tin apollo gateway too? Can you pls give an idea when to expect it?

**Comment by trevor-scheer** [comment]
This is not planned for gateway. If you're interested in Federation and `@defer` support, check out [Router](https://www.apollographql.com/docs/router) (I promise you'll like it).

**Comment by magicmark** [comment]
@trevor-scheer 👋 do you think this is something y'all would reconsider?

I'm very sympathetic to not wanting to do active feature development in two places, and giving people an exclusive carrot to migrate to Router. (We do this ourselves a lot for internal migrations :P)

However, we don't run any other Rust services at Yelp, and are will likely be unable to do so in the foreseeable future. The cost to spinning up and maintaining a service in a new language is super high:
- we have lots of common logic implemented in shared middlewares in our supported languages that would require porting to rust / rhai
- we need folks who can do long term maintenance and troubleshooting bugs and perf issues in Rust

Also - we had to monkey patch some custom logic into our node router service (https://github.com/apollographql/federation/issues/2603) - would Router be extensible enough to support this?

I'm afraid we're a little stuck on `@apollo/gateway` for the foreseeable future. We're just getting started launching production subgraphs, so i'd love to chat about this, and see there's any wiggle room here :)

Thanks!
