### ISSUE TITLE
buildSubgraphSchema errors with duplicated query type

### ISSUE THREAD

**Issue by MrDesjardins** [apollographql/federation#1220]
**Repro**
1) Go to https://codesandbox.io/s/graphql-federation-buildsubgraphschema-version2-692el?file=/src/index.js
2) Open the Terminal from Codesandbox and execute: `node src/index.js`

**Expectation**
To merge all schema into 1 string

**Current Result**
An error saying "GraphQLSchemaValidationError: There can be only one type named "Query"."

**Related Issue discussed with the graphql-tools**
https://github.com/ardatan/graphql-tools/issues/3888 

**What am I trying to accomplish (context)?**
I am migrating an existing schema to be consumed into a Federated system. I am converting the code that used `merge-graphql-schemas` to use the `buildSubgraphSchema` instead to be able to use [Federated types](https://www.apollographql.com/docs/federation/federation-spec/). My code is actually pretty close to the tutorial from that page: https://www.apollographql.com/docs/federation/subgraphs/#combined-example but it has an exception when I try to use a Federated annotation.

** Versions **
OS: Mac OS 11.6
"@apollo/subgraph": "^0.1.4",
"@graphql-tools/load-files": "^6.5.2",
"@graphql-tools/merge": "^8.2.1",
"@graphql-tools/schema": "^8.3.1",
"@graphql-tools/utils": "^8.5.3",
NodeJS: 14.5.0

**Comment by trevor-scheer** [comment]
I forked your sandbox (which, 🙇 for that!) and found that the error is correct. If you take a look at the changes I made to the fork, you can see in the logs that `concatAST` is not handling the merging of the `Query` type for you, so there are two `Query` definitions, which is invalid. If you instead change one of the `type Query ...` to `extend type Query ...` that resolves the issue you're running into.

https://codesandbox.io/s/graphql-federation-buildsubgraphschema-version2-forked-dy5r5?file=/src/index.js

**Comment by MrDesjardins** [comment]
Thank you @trevor-scheer . I was wondering. What is the official recommendation to merge GraphQL files for subgraph? I was under the impression that the `extends type` was for extending type among GraphQL servers under a Federated graph and not necessarily a way to avoid conflict when stitching many files into one.

**Comment by trevor-scheer** [comment]
There may be tooling that exists for this (https://www.graphql-modules.com/docs/index/ comes to mind, though I have no experience with it and can't say whether or not it solves your problem). However, my recommendation would be to use `extend`, as this is a perfectly valid use for it. The `extend` keyword is native GraphQL syntax and isn't proprietary to Federation in any way. You might go as far as having some "base" graphql file which defines the `Query` type which all of your other files extend from, if you're looking for consistency.

```graphql
type Query
```

```graphql
extend type Query {
  products: [Product]
}
```

```graphql
extend type Query {
  reviews: [Review]
}
```
