### ISSUE TITLE
Deprecated federation 2 `@apollo/federation` package

### ISSUE THREAD

**Issue by pcmanus** [apollographql/federation#1228]
Following up from https://github.com/apollographql/federation/pull/1208, the `@apollo/federation` is not part of the federation 2 code anymore and thus new versions won't be published. We did publish a version of this package for federation 2 alpha so this ticket is to ensure we deprecate that version with `npm` and anything else that ensures users are not lost with this removal.

**Comment by pcmanus** [comment]
@abernix I never really deprecated packages with npm and I think you have far more experience with all that. Would you be ok handling this?

**Comment by trevor-scheer** [comment]
Deprecated both `2.0.0-alpha.x` versions with the following note. Happy to update it per any suggestions.
![image](https://user-images.githubusercontent.com/29644393/142902167-51f86ab5-09f1-45cf-8e69-95f3004e36a4.png)
