### ISSUE TITLE
@apollo/gateway and @apollo/subgraph missing recent changelog entries

### ISSUE THREAD

**Issue by setchy** [apollographql/federation#1263]
@apollo/gateway [CHANGELOG.md](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md ) appears to be missing release notes for versions:
* 0.43.0
* 0.43.1
* 0.44.0
* 0.44.1
* 0.38.2

@apollo/subgraph [CHANGELOG.md](https://github.com/apollographql/federation/blob/main/subgraph-js/CHANGELOG.md) appears to be missing release notes for versions:
* 0.1.4
* 0.1.5

This is currently breaking tooling like Renovate Bot from attaching release notes to dependency update PRs

**Comment by trevor-scheer** [comment]
Thanks for the heads up @setchy. This must be a byproduct of our two branches now - all of those entries are being committed to the `version-0.x` branch. I'll see if there's anything we can do about this.

**Comment by abernix** [comment]
I think that if we actually publish releases from both branches (0.x and 2.x) to GitHub Releases, it might actually be a reasonable solution for this (and also allow folks the ability to subscribe to GitHub Releases, either via RSS, or other means — like the GitHub API).

**Comment by abernix** [comment]
Which is  what @setchy's now-closed #636 was suggesting 😄.  It was closed since Renovate actually supports _the way we were doing it prior to having two release branches_, but now perhaps we should re-open that and action it.

**Comment by setchy** [comment]
Any further thoughts on how this could best be handled @trevor-scheer @abernix?

I have been manually checking CHANGELOG files each time a Renovate PR gets raised to see if there is anything major in each 0.x release.  The 0.46.0 release a few days ago was a pretty juicy.

**Comment by trevor-scheer** [comment]
@setchy apologies for the manual-ness this split has introduced. Aspirationally, I've been investigating a tool called [changesets](https://github.com/changesets/changesets) for managing changelogs and releases, but I intend to validate it on a new and smaller repo first. I know that isn't helpful in the immediate.

**Comment by setchy** [comment]
Closing this issue now that Fed2 is GA
