### ISSUE TITLE
Duplicate Parallel calls to federated services with Federation 2

### ISSUE THREAD

**Issue by AneethAnand** [apollographql/federation#1316]
Query planner generates - Duplicate parallel calls to the federated services
Repository to reproduce the error (https://github.com/AneethAnand/federation2)

### Graphql Query
```
query test {
      viewer {
        user {
          user1
          user2
          id
          user3
          network {
                  id
              network1
          }
          user4
          user5
          user6
          user7
          user8
        }
        viewer1
        viewer2
        viewer3
    }
}
```
#### Actual QueryPlan
```
QueryPlan {
  Parallel {
    Fetch(service: "A1") {
      {
        viewer {
          user {
            user1
            user2
            id
            user3
            network {
              id
              network1
            }
            user4
            user5
            user6
            user7
            user8
          }
          viewer1
          viewer2
          viewer3
        }
      }
    },
    Fetch(service: "V1") {
      {
        viewer {
          user {
            user2
            id
            user3
            network {
              id
              network1
            }
            user4
            user5
            user6
            user7
            user8
          }
          viewer1
          viewer2
          viewer3
        }
      }
    },
  },
}
```
#### Expectation 
```
    Fetch(service: "A1") {
      {
        viewer {
          user {
            user1
            user2
            id
            user3
            network {
              id
              network1
            }
            user4
            user5
            user6
            user7
            user8
          }
          viewer1
          viewer2
          viewer3
        }
      }
    }
```

###  Remove one of the field say "viewer3" in the query, the gateway works as expected.
```
QueryPlan {
  Fetch(service: "A1") {
    {
      viewer {
        user {
          user1
          user2
          id
          user3
          network {
            id
            network1
          }
          user4
          user5
          user6
          user7
          user8
        }
        viewer1
        viewer2
      }
    }
  },
}
```

**Comment by pcmanus** [comment]
Thanks for the report and sorry for the inconvenience. Created #1319 with a fix.

**Comment by AneethAnand** [comment]
@pcmanus  Can you publish the changes for the fix?  It not merged to the version 2.0.0-alpha.1

**Comment by AneethAnand** [comment]
@abernix / @pcmanus  Can you tell me how can I point query-planner dependency to your private federation mono-repo? I tried using query-planner-js's package.json but it is dependent on internal-js and query-graph. Not sure if the federation repo has a package.json that points to all those 3 folders.

**Comment by abernix** [comment]
@AneethAnand Those are all referenced in this repository.  This code doesn't live in any private federation monorepo.  What you might be looking for is a release to be cut that includes this fix, which is something that hasn't yet been done but I understand should be coming in the next couple days.  (Is that right, @pcmanus?)

**Comment by cpeacock** [comment]
@AneethAnand We should be cutting that new release sometime this week.

**Comment by AneethAnand** [comment]
Thanks for the update @abernix and @cpeacock !

**Comment by pcmanus** [comment]
@AneethAnand Sorry for the delay, but `2.0.0-alpha.3` was published on Friday and contains that fix if you'd like to give it a shot. Thanks again for the report!

**Comment by AneethAnand** [comment]
@pcmanus No problem I saw the newer version published on Friday and we have already started using it. Thanks again!
