### ISSUE TITLE
Support Node 17

### ISSUE THREAD

**Issue by 3x071c** [apollographql/federation#1382]
I can't install the Apollo CLI tools (with some strict flags on) because I'm running the latest, non-LTS Node version (the engines string specifically only allows versions below 17). Are there any known incompatibilities, or is this being done because said version isn't LTS and therefore might be more prone to bugs? If it is the latter, I would suggest removing the upper limitation, since I don't think a developer would accidentally run the bleeding edge version of their tools and blame this project for it. 👍

**Comment by setchy** [comment]
#1541

**Comment by trevor-scheer** [comment]
Fixed via #1541 and #1648 in their respective branches. Released in `v0.x` federation packages now, and to be released in `v2` packages whenever it releases next!
