### ISSUE TITLE
[js-repo-migration] Move federation issues to this repository

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#144]
Follows up: #134 

Currently, there are a lot of Issues on the Apollo Server GitHub repository which touch on federation-related concerns.  Those issues represent the current conversations around Apollo Federation and Apollo Gateway functionality and also act as the pulse of the community.  They need to be moved over here, either by manual or automated processes.  Today, they all exist on the [`federation` label](https://github.com/apollographql/apollo-server/labels/%F0%9F%91%A9%E2%80%8D%F0%9F%9A%80%20federation) of the `apollo-server` repository, but that should become more granular once they are moved here.

**Comment by Enrico2** [comment]
I'd like to avoid exploding the number of issues we're going to have in this repository. It is my personal goal to address things as they come and prioritize accordingly.
I'd like to us to not moving everything automatically, and actually go over them and see if we're ever going to fix them, the ones that we decide should stay open should move, and others closed with a proper explanation. IIUC this repo is going to be focused on the "new" work, and not update the old stuff, and so if those issues are good to inform us of what we need to take into account for the new work, that's great, but those can be collated to a single issue.
