### ISSUE TITLE
Provide naming of subgraph GraphQL operations instead of sending them as anonymous operations

### ISSUE THREAD

**Issue by theJC** [apollographql/federation#1544]
Federated queries when sent to the subgraphs are anonymous and not named, therefore most of the available observability tooling out of the box is not very useful in differentiating the various requests when monitoring at the subgraph level.

Please add a mechanism that names and/or provide a function to allow federation customers to provide a naming convention on the queries being sent to their subgraphs to allow observability and telemetry tooling based on operationName to work out of the box.

A few initial thoughts/ideas on ways we would like to have these operations named with the original operation name, append/suffixing it with either or both:
- the subgraph name
- a consistent/stable identifier of the step within the query plan that the call corresponds to

ie:
Query to the federated gateway:
```
query FindMyPhone($input: FindMyPhoneInput!) {
  findMyPhone(input: $input) {....
```

Currently actual behavior results in a subgraph query:  (note that it is anonymous/not named)
```
query($FindMyPhoneInput!){...
```

Wanted behavior, subgraph query is named/not anonymous:
```
query FindMyPhone_subquery_step1a($FindMyPhoneInput!){...
```

**Comment by abernix** [comment]
Thanks for opening this.

This should be fixed by #1550.  This will go out in a new release of the `2.x` package next week.
