### ISSUE TITLE
@apollo/gateway-preview.1 has wrong compiled source

### ISSUE THREAD

**Issue by hayes** [apollographql/federation#1576]
I'm not 100% sure I understand the issue correctly, but `dist` imports `@apollo/federation` while in `src` it imports `@apollo/federation-internals`.  Neither package is in the dependency list in the current package.json.

Currently this results in an module not found error for `@apollo/federation`, but I suspect there is a larger issue here with the release process (Maybe this was a manual release, and the last build was run of the stable release branch?)

It looks like `dist` directory of `@apollo/gateway-preview.1` was not built from the version in the `src` directory:
<img width="766" alt="Screen Shot 2022-03-09 at 1 20 55 PM" src="https://user-images.githubusercontent.com/816527/157538557-29dfcdb3-88f3-44e5-9feb-6b6d94f6c87f.png">
<img width="762" alt="Screen Shot 2022-03-09 at 1 23 51 PM" src="https://user-images.githubusercontent.com/816527/157538564-2d7f1988-86bd-4244-b006-3179400b1059.png">

**Comment by cpeacock** [comment]
@hayes thanks for the report, this was definitely a manual publish because our CI/CD process got stuck.  We're fixing, and thank you for the report!  We're going to be rerunning the pipeline shortly and this should fix the issue, please reopen if you see it again after the next release ship.

**Comment by abernix** [comment]
@hayes We just published a `2.0.0-preview.2` (on the `latest-2` dist-tag) which should have a fix for this.  Please let us know if it persists and thanks again for letting us know about this!

**Comment by hayes** [comment]
thanks!
