### ISSUE TITLE
Overlap of `@key(fields: a { b })` and `a: A @provides(fields: "c")` results in composition error

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#1603]
Reproduction: https://stackblitz.com/edit/nodemon-86wmhe?file=README.md

**Subgraph ONE containing the "parent" entity**

```graphql
type Query {
  registry: ProductRegistry
}

type ProductRegistry @key(fields: "id status") {
  id: ID!
  status: String!
  dateAdded: String
}
```

**Subgraph TWO with the "child" entity**

The child entity doesn't have its own id. Instead it uses the id of the related "parent" entity.

However, this subgraph also can `@provide` another field on the "parent" entity.

```graphql
type Query {
  product: Product
}

type Product @key(fields: "registry { id }") {
  registry: ProductRegistry! @provides(fields: "dateAdded")
  otherField: String
}

type ProductRegistry @key(fields: "id status") @extends {
  id: ID! @external
  status: String! @external
  dateAdded: String @external
}
```

**The problem**

Using both the compound key and the `@provides` causes this error:

```
[TWO] Product -> A @key selects registry, but Product.registry was either created or overwritten by TWO, not TWO
```

**Versions**

```
"@apollo/gateway": "^0.48.3",
"@apollo/subgraph": "^0.3.3",
"apollo-server": "^3.6.4",
"graphql": "^16.3.0",
```

**Expected behavior**

This should compose (it does it Fed2).

**Comment by trevor-scheer** [comment]
Fixed via #1604 and released in the latest v0 federation packages.
