### ISSUE TITLE
Fed2 query planning regression with @requires

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#1725]
Reproduction: https://stackblitz.com/edit/basic-federation-o5kzav?file=readme.md

The issue is triggered by including the `computed2` field—without it, the query plans are identical in fed1 and fed2.

This was reported by a customer.

**Comment by pcmanus** [comment]
Thanks a lot for the simple reproduction (which I shamelessly stole as a unit test). Created #1732 with a fix.
