### ISSUE TITLE
Allow `schema` option in `buildSubgraphSchema` from @apollo/subgraph

### ISSUE THREAD

**Issue by stringbeans** [apollographql/federation#1745]
Hi there!

First off, amazing work with Apollo Federation 2!!

I'm currently working with a NestJS project where I can gain access to a pre-built `schema` object but I don't have direct access to typedefs or resolvers map. It would be great if I could "transform" the existing schema into a subgraph schema. I'm thinking of something like so:

```
const subgraphSchema = buildSubgraphSchema({
  schema
})
```

I also feel it would be a better developer experience if the developer didnt need to add `extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable"])` to the top of the typedefs in order to opt-in to federation 2. since the `buildSubgraphSchema` function is new to federation 2 (i think?), would it be safe for that function to add it directly? 

Cheers!

**Comment by stringbeans** [comment]
thank you @pcmanus for your in-depth response, really appreciate it :pray:

**Comment by pcmanus** [comment]
I actually only just realised that we already have an old ticket about this as #358, and there is some history linked from there.

So I'm going to close this ticket in favour of that pre-existing ticket. But in any case, this confirm that there is interest for adding that flexibility and so agreed we should :).

**Comment by smyrick** [comment]
I will add that modifying an existing schema would really only be able to add the Federation type definitions. The Apollo function `buildSubgraphSchema` wouldn't have enough context to know what other resolvers you might want to add like `__resolveReference`. So really what you need to do is just add some directives to an existing schema. That can be done today with tools like [graphql-tools merge](https://the-guild.dev/graphql/tools/docs/schema-merging).

I have a working example of how to do exactly that here: https://github.com/apollosolutions/add-federated-types

This takes some existing SDL and adds merges it with the Federation spec. It will not be able to add resolvers for you but it is a way to "automatically" include the `@link` directives if you want or add `@key` to certain types
