### ISSUE TITLE
Add node18 support

### ISSUE THREAD

**Issue by benweatherman** [apollographql/federation#1752]
- node18 has officially been released! We should officially support that.
- node12 is out of LTS at the end of April ~, so official support could be deprecated.~. It would be a major version bump to deprecate node12, so we'll continue supporting that for now.

**Comment by RicardJoenck** [comment]
Greetings! Sorry to barge in, but is there any ETA for this to be released? Thank you!

**Comment by benweatherman** [comment]
Howdy @RicardJoenck and thank you for barging in 😄 We're going through some planning for a `2.1.0` now, I'd expect it sometime in the next few weeks. I'll get back to you tomorrow with a more exact timeframe.

**Comment by benweatherman** [comment]
To give more context: the major functionality for the `2.1.0` release is promoting directives from subgraphs into the composed supergraph schema https://github.com/apollographql/federation/issues/1893. That feature requires a bit more work before we're ready to merge it. In the past, we'd likely release the node 18 update now since the change is ready, but we're trying to provide a little more value for each upgrade.

It's still unclear exactly when the `2.1.0` release will happen, my best guess is still within the next few weeks. I'll continue to update here as we get more clarity.

Apologies for an unsatisfactory answer, but wanted to give you the info I have.
