### ISSUE TITLE
Apollo gateway studio issue with graphql-scalars

### ISSUE THREAD

**Issue by jayraj-lw** [apollographql/federation#176]
When I started the gateway server in managed mode at that time I'm getting error like below

```
[WARN] Tue Sep 22 2020 11:55:08 GMT+0530 (India Standard Time) apollo-gateway: Error checking for schema updates. Falling back to existing schema. { FetchError: invalid json response body at https://storage.googleapis.com/engine-partial-schema-prod/2559ac17-d8ec-4401-baf4-ea071c6bb664/current/v1/composition-config-link reason: 
Unexpected token < in JSON at position 0
    at (anonymous function).then.buf (/home/logicwind/jayraj/vs_projects/LW/jnxn-server/gateway/node_modules/minipass-fetch/lib/body.js:77:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'FETCH_ERROR',
  errno: 'FETCH_ERROR',
  type: 'invalid-json' }
```

There will be any issue ? If I have used any package for scalars which are not provided by default. I have used the `https://www.npmjs.com/package/graphql-scalars` package.

**Comment by abernix** [comment]
@jayraj-lw What version of `@apollo/federation` and `@apollo/gateway` are you running?  Have you gone through the [Managed federation setup](https://www.apollographql.com/docs/studio/managed-federation/setup/) steps?  (This error might occur when no schema has been pushed.)

**Comment by jayraj-lw** [comment]
> @jayraj-lw What version of `@apollo/federation` and `@apollo/gateway` are you running? Have you gone through the [Managed federation setup](https://www.apollographql.com/docs/studio/managed-federation/setup/) steps? (This error might occur when no schema has been pushed.)

**Comment by jayraj-lw** [comment]
> @jayraj-lw What version of `@apollo/federation` and `@apollo/gateway` are you running? Have you gone through the [Managed federation setup](https://www.apollographql.com/docs/studio/managed-federation/setup/) steps? (This error might occur when no schema has been pushed.)

The version of `@apollo/federation` and `@apollo/gateway` I'm running is 0.20.4. And yes I've go through the managed federation setup and schemas are also pushed to the apollo studio.

RIght now I'm getting this error:-
```
Error checking for changes to service definitions: Could not communicate with Apollo storage: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message></Error>
This data graph is missing a valid configuration. Could not communicate with Apollo storage: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message></Error>
```

**Comment by Enrico2** [comment]
@jayraj-lw I'm not at all an expect in this part of the code, trying to help anyway :)
that `Access denied` is somewhat suspect. Did you add an API key to your Apollo Server as described [here](https://www.apollographql.com/docs/studio/managed-federation/setup/#4-connect-the-gateway-to-studio)?

**Comment by abernix** [comment]
@jayraj-lw If you contact Apollo Studio support, they should be better equipped to help on on this matter.  We don't look at account specific details involving API keys and permissions here on the open-source side of things, but they'll be happen to help you debug this.

**Comment by lfuenzalida2** [comment]
I get the same two errors sometimes when i try to build my app (based on MS), and sometimes i just shut down the app, reload it (without re-building it) and it works completly fine. It's almost like gateway skips its dependencies

**Comment by lfuenzalida2** [comment]
I'm running Apollo Federation ^0.20.3, Apollo Gateway ^0.20.0 and Apollo Server ^2.17.0
