### ISSUE TITLE
Directives which are located on INLINE FRAGMENT are skipped and are not sent to the service

### ISSUE THREAD

**Issue by evgen4uk** [apollographql/federation#177]
I'm using gateway v0.20.1 and here is my schema:

```
directive @fragmentDirective on INLINE_FRAGMENT
directive @fieldDirective on FIELD

interface Human {
    name: String!
}

type User implements Human {
    name: String!
    email: String!
}

type Query {
    selectHuman:[Human]
}
```

After sending the following query, @fragmentDirective will be skipped and will not come to the service, the @fieldDirective is NOT skipped
```
{
 selectHuman{
    name
    ... on User @fragmentDirective {
      email @fieldDirective
    }
  }
}
```

After debugging I found that after parsing the request, the directive is present in the operation context, please see
<img width="1094" alt="directive is present in operation context" src="https://user-images.githubusercontent.com/7079780/93902946-cc70e700-fd00-11ea-9624-f677547a57bf.png">
<img width="1236" alt="directive is present in seletion set" src="https://user-images.githubusercontent.com/7079780/93903002-d8f53f80-fd00-11ea-82e0-bf0f4b7fe49c.png">

But it was lost after building query plan
<img width="1175" alt="directive is absent in query plan" src="https://user-images.githubusercontent.com/7079780/93903129-f88c6800-fd00-11ea-9d68-583203e23c24.png">

I will appreciate any help or suggestions. 
Thank you!

**Comment by Enrico2** [comment]
@evgen4uk Thanks for the report! I've gone ahead and fixed it in #178, and I'll let you know here when we've released a version that includes this fix. Should be this week. It'll be version `0.20.3`

**Comment by evgen4uk** [comment]
@Enrico2 thank you very much for your quick fix. I really appreciate it.

**Comment by Enrico2** [comment]
Hey @evgen4uk, `0.20.3` has been released, let us know if you still have this bug.
(FYI #179 is still open, hopefully you're not relying on directives on fragment spreads)
