### ISSUE TITLE
Uplink Fallback Function

### ISSUE THREAD

**Issue by sMorm** [apollographql/federation#1801]
When there are Uplink failures, whether it's an internal outbound networking issue or Uplink failing to resolve, there's a lot of value in being able to provide a fallback function that returns the last working schema. Although [additional Uplink endpoints can be provided](https://www.apollographql.com/docs/federation/managed-federation/uplink/#environment-variable), it adds to the list of round-robin candidate, where we don't always want it to be. Providing a way to provide a fallback function would give us the flexibility to fallback to the last healthy schema from a local source such as a cache, or even other up and running gateway pods in the same cluster.

Alternatively, @lennyburdette's [resiliency solution](https://github.com/apollosolutions/managed-federation-resiliency/pull/5/files#diff-c7c29c4fdc9870447c7b403009bbfc2bd35ca20a232ab6b1919b7226e5722ad6) is another option where a fallback schema is provided via the constructor. Although this works, we want to prioritize Uplink, over having to hit our fallback to populate the constructor on Gateway startup.

**Comment by benweatherman** [comment]
howdy @sMorm! Thanks for a good suggestion! I've put up a potential solution, but I'd love your feedback on the interface and how it works if you have some time
