### ISSUE TITLE
Updating to Apollo 2 gives error this.node not a function

### ISSUE THREAD

**Issue by blazestudios23** [apollographql/federation#1872]
I just updated to federation 2. 

I made no other changes. 

I get the following error:

```
TypeError: this.node is not a function

error: uncaughtException this.node is not a function {"app":"gateway-api","environment":"local","stack":"TypeError: this.node is not a function\n
```

I'm using grpahql 15.8. 

I tried to install /subgraph on a sub service and I get the exact same error. 

The federation service is very bare bones, but the sub service has a large quantity of libraries. 

However this has to be related to Federation 2.0 as that is what causes both to throw these errors. 

Is it possible this is caused from not having a node type defined in the graph? 

This was caused by running 

```
npm i @apollo/federation
```

then starting the server. 

Here are all the other dependencies in the service:

```
{
  "devDependencies": {
    "@types/compression": "^1.7.2",
    "@types/cookie-parser": "^1.4.3",
    "@types/express-jwt": "^6.0.4",
    "@types/express-rate-limit": "^6.0.0",
    "@types/hpp": "^0.2.2",
    "@types/jsonwebtoken": "^8.5.8",
    "@types/node": "^17.0.34",
    "@types/signale": "^1.4.4",
    "@types/uuid": "^8.3.4",
    "@types/wait-on": "^5.3.1",
    "@typescript-eslint/eslint-plugin": "^5.25.0",
    "@typescript-eslint/parser": "^5.25.0",
    "dotenv": "^16.0.1",
    "eslint": "^8.15.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.0.0",
    "prettier": "^2.6.2",
    "ts-node": "^10.7.0",
    "ts-node-dev": "^1.1.8",
    "typescript": "^4.6.4"
  },
  "dependencies": {
    "@apollo/gateway": "^2.0.2",
    "@apollo/rover": "^0.6.*",
    "@sentry/node": "^6.13.3",
    "apollo-server-express": "^3.7",
    "bcryptjs": "^2.4.3",
    "compression": "^1.7.4",
    "cookie-parser": "^1.4.6",
    "express": "^4.18.1",
    "express-rate-limit": "^6.4.0",
    "graphql": "^15.8.0",
    "graphql-middleware": "^6.1.26",
    "graphql-shield": "^7.5.0",
    "helmet": "^5.1.0",
    "hpp": "^0.2.3",
    "jsonwebtoken": "^8.5.1",
    "jwks-rsa": "^2.1.2",
    "moment": "^2.29.3",
    "nps": "^5.10.0",
    "nps-utils": "^1.7.0",
    "signale": "^1.4.0",
    "subscriptions-transport-ws": "^0.11.0",
    "uuid": "^8.3.2",
    "wait-on": "^6.0.1",
    "winston": "^3.7.2",
    "winston-logzio": "^5.1.4",
    "xss-clean": "^0.1.1"
  },
  "engines": {
    "node": "14.x",
    "npm": "7.x"
  }
}

```

**Comment by trevor-scheer** [comment]
v2+ Federation packages have a peer dependency on `graphql@^16.0.0`. You should be seeing warnings or errors when you run your install script.

**Comment by blazestudios23** [comment]
That causes issues as other libraries have a peer dependency on graphql@^15.* like graphql-tools which seems to be install by either apollo-server-express ^3.7.0 or @apollo/gateway ^2.0.2. 

I've removed all other GraphQL related libraries.

**Comment by trevor-scheer** [comment]
Can you provide the output of `npm ls graphql`? It'll be helpful to know what the specific conflicts are. I don't have experience doing this myself, but you might have success working around the errors for now with `npm install --force`.

Apollo Server ^3.7 also claims compatibility with v16. I do see some incompatibilities with dev dependencies but nothing in  the runtime. It seems to come down to `relay-compiler` (from what I'm seeing), which is depended on by some of the codegen tooling.

**Comment by blazestudios23** [comment]
Ok, that makes sense. I got it to start, still working on updating a subgraph to Federation 2, so can't tell if it actually works or not. 

But I do get the following warnings::


```
npm WARN @graphql-tools/merge@8.0.1 requires a peer of graphql@^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-tools/utils@8.1.1 requires a peer of graphql@^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-tools/mock@8.2.1 requires a peer of graphql@^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-tools/schema@8.1.1 requires a peer of graphql@^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @graphql-tools/utils@8.1.1 requires a peer of graphql@^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tag@2.12.5 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by trevor-scheer** [comment]
The `npm ls graphql` output will be a lot more helpful since it prints out a tree and makes it easier to identify which leaves in the dep tree are problematic.

i.e. `@graphql-tools/utils` actually has a current version which supports v16, but I don't know what's depending on specifically `@graphql-tools/utils@8.1.1`.
