### ISSUE TITLE
Fed 1 with gateway 2 can break on query plans with interface fragments

### ISSUE THREAD

**Issue by smyrick** [apollographql/federation#1903]
This is related to this change in the query plan code about expanded fragments: https://github.com/apollographql/federation/issues/1894

Repro: https://stackblitz.com/edit/apolloeg-supergraph-error?file=README.md

---------------------

Service A has the following schema

```graphql
type Query {
  a: [URI]
}

interface URI {
  value: String!
}

type One implements URI {
  value: String!
}
```

Service B has the following schema

```graphql
type Query {
  b: [URI]
}

interface URI {
  value: String!
}

type Two implements URI {
  value: String!
}
```

A client can make a valid query with the following fragment defintion

```graphql
{
  a {
    ...UriSelection
  }
  b {
    ...UriSelection
  }
}

fragment UriSelection on URI {
  ...on One {
    __typename
    value
  }
  ...on Two {
    __typename
    value
  }
}
```

The fragment is valid when looking at the supergraph schema because both `One` and `Two` implement `URI`.

However when the query planner in gateway v2 creates a fetch node it doesn't properly handle fragments so it creates this query plan

```graphql
QueryPlan {
  Parallel {
    Fetch(service: "a") {
      {
        a {
          __typename
          ... on One {
            __typename
            value
          }
          ... on Two {
            __typename
            value
          }
        }
      }
    },
    Fetch(service: "b") {
      {
        b {
          __typename
          ... on One {
            __typename
            value
          }
          ... on Two {
            __typename
            value
          }
        }
      }
    },
  },
}
```

You will notice that the fetch to Service A includes a reference to type `Two` and the fetch to Service B includes a reference to type `One` even though they know nothing about these types.

This has been fixed in Fed 2 with the `@join__implements` directive as the query planner knows not to include those selections on type implementations not in the subgraph.

**Comment by pcmanus** [comment]
This is a limitation of fed1 supergraph: they simply don't have enough information to deal with that case correctly. This is why we added `@join__implements` and there is no other fix than to re-compose with fed2 composition to obtain a fed2 supergraph with proper information.

I'll note that the fed1 query planner generates the exact same (incorrect) query plan on this example, so this isn't a regression of fed2.
