### ISSUE TITLE
Error when querying parent field's sibling type in a fragment with fed1 schema

### ISSUE THREAD

**Issue by benweatherman** [apollographql/federation#1907]
Given the following subgraph and operation, the following error is returned when running the query

```
We should have an edge from Fruit(fruit-subgraph) for __typename
```

It _seems_ like the issue arises because the fragment is selecting a sibling type to `Apple`. Basically the `... on Banana` part of the fragment could never happen because an apple will never be a banana. If you were to write that directly instead of via fragment, you'd get an error.

Note that this works correctly when using fed2 composition. It's only an issue running a fed2 gateway with a fed1 supergraph.

### Subgraph Schema

```graphql
  interface Fruit {
    edible: Boolean!
  }
  
  type Banana implements Fruit {
    edible: Boolean!
    inBunch: Boolean!
  }
  
  type Apple implements Fruit {
    edible: Boolean!
    hasStem: Boolean!
  }
  
  type Query {
    fruit: Fruit!
  } 
```

### Operation

```graphql
fragment OrangeYouGladIDidntSayBanana on Fruit {
  ... on Banana {
    inBunch
  }
  ... on Apple {
    hasStem
  }
}

query Fruitiness {
  fruit {
    ... on Apple {
      ...OrangeYouGladIDidntSayBanana
    }
  }
}
```

### Source

Here's the bit of code that's triggering the error https://github.com/apollographql/federation/blob/a0c734348eadb153848911008f3ffcaa160b38e8/query-graphs-js/src/graphPath.ts#L584-L614

## Working example

An example that reproduces the error can be found at https://stackblitz.com/edit/apolloeg-supergraph-error-qbodxl

**Comment by pcmanus** [comment]
Pushed relatively simple fix at #1908.
