### ISSUE TITLE
Apollo gateway: Custom fetcher to RemoteGraphQLDataSource doesn't work correctly

### ISSUE THREAD

**Issue by Bhoomikapanwar** [apollographql/federation#191]
Description: Passing make-fetch-happen (Fetch-API complaint) as the custom fetcher to RemoteGraphQLDataSource doesn't work correctly. 

Package - "@apollo/gateway": "^0.20.4"

The expected behavior: The fetcher should correctly fetch from Downstream services.

The actual behavior: The fetcher doesn't work and throws an error "Only absolute urls are supported" instead.

Reproduction setup: https://github.com/Bhoomikapanwar/gateway-playground-1.git

**Comment by saravind-hotstar** [comment]
@Bhoomikapanwar So for customizing the timeout at remote graphql sources, what is the final way to do it. Really appreciate your help here
