### ISSUE TITLE
create a top level `CHANGELOG.md` that just links to the other changelogs

### ISSUE THREAD

**Issue by EverlastingBugstopper** [apollographql/federation#1919]
would it mess with tooling at all to just have a top level `CHANGELOG.md` that documents where all of the changelogs are for the various versions and packages?

**Comment by EverlastingBugstopper** [comment]
i've opened a PR on `federation-rs` to do exactly this we want folks to refer to the changelogs in this repository if they need to since most other changes in `federation-rs`-land are purely implementation details. https://github.com/apollographql/federation-rs/pull/143

**Comment by pcmanus** [comment]
No clue about the "would it mess with tooling", but assuming this doesn't, this sound to me like a great idea.

**Comment by EverlastingBugstopper** [comment]
i just know some folks have like automated `CHANGELOG.md` generators or release note handlers.... i don't think that's the case here if it doesn't sound like an issue to you
