### ISSUE TITLE
Need help - updating apollo gateway from 0.26.1 to 2.0.0

### ISSUE THREAD

**Issue by rajarajan1985** [apollographql/federation#1927]
I have updated my environment

From this
@apollo/gateway: “0.26.1”
@apollo-server-lambda: “2.22.2”
graphql: 15.5.0

To this:
@apollo/gateway: “2.0.0”,
apollo-server-lambda": “^3.0.0”,
“graphql”: “^16.0.0”,

But the existing code setup is not working anymore due to an error that occurred during the Apollo server startup.

2022-06-24T04:43:12.696Z ERROR An error occurred during Apollo Server startup. All GraphQL requests will now fail. The startup error was: When a manual configuration is not provided, gateway requires an Apollo configuration. See [Managed federation overview - Apollo GraphQL Docs](https://www.apollographql.com/docs/apollo-server/federation/managed-federation/) for more information. Manual configuration options include: serviceList, supergraphSdl, and `experimental_updateServiceDefinitions

ERROR Invoke Error
{
“errorType”: “Error”,
“errorMessage”: “This data graph is missing a valid configuration. More details may be available in the server logs.”,
“stack”: [
“Error: This data graph is missing a valid configuration. More details may be available in the server logs.”,
" at ApolloServer._ensureStarted (/var/task/node_modules/apollo-server-core/dist/ApolloServer.js:317:27)“,
" at ApolloServer.ensureStarted (/var/task/node_modules/apollo-server-core/dist/ApolloServer.js:331:20)”,
" at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:46:24",
" at Runtime.handler (/var/task/app.js:18:10)“,
" at TransactionShim.applySegment (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1430:20)”,
" at Runtime.wrappedHandler (/opt/nodejs/node_modules/newrelic/lib/serverless/aws-lambda.js:188:20)“,
" at TransactionShim.applySegment (/opt/nodejs/node_modules/newrelic/lib/shim/shim.js:1430:20)”,
" at Runtime.transactionWrapper (/opt/nodejs/node_modules/newrelic/lib/shim/transaction-shim.js:621:17)“,
" at Runtime.patchedHandler [as handler] (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:122:25)”,
" at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)"

Please advise.

**Comment by rajarajan1985** [comment]
Hi @benweatherman, Thanks for your help.

The issue is now resolved. Actually, I have screwed up the arguments passed into the apollo server constructor. I got clarified from this doc https://www.apollographql.com/docs/apollo-server/api/apollo-server/. 

I have also updated the gateway version to 2.0.5.

**Comment by benweatherman** [comment]
Great to hear you were able to resolve the issue @rajarajan1985!
