### ISSUE TITLE
node-fetch runtime dependency is missing in @apollo/gateway v2.0.5

### ISSUE THREAD

**Issue by marcelkottmann** [apollographql/federation#1961]
We are currently upgrading our application to Federation v2. After upgrading the necessary packages, we found out that node-fetch is a runtime dependency of @apollo/gateway (current, v2.0.5) and is missing in its package.json.

We therefore get a runtime error:
```bash
Error: Cannot find module 'node-fetch'
Require stack:
- /var/task/node_modules/@apollo/gateway/dist/executeQueryPlan.js
- /var/task/node_modules/@apollo/gateway/dist/index.js 
```

Strange enough the only node-fetch related thing in the package.json are the typings of node-fetch `@types/node-fetch` which is sorted into the `dependencies`, although typing packages typically are  listed in the `devDependencies`-section.

See https://github.com/apollographql/federation/blob/%40apollo/gateway%402.0.5/gateway-js/package.json

Adding node-fetch@2.6.7 as a dependency in our projects `package.json` fixed this problem for us, but is considered a workaround, because our codebase does not use `node-fetch`.

**Comment by benweatherman** [comment]
howdy @marcelkottmann! Are you able to share the package file (at least the dependencies) and which package manager is being used? Can you also share more of the stacktrace, specifically the line the error is coming from?

> although typing packages typically are listed in the devDependencies-section

I agree about this, it should be moved over to `devDependencies`

Doing some minimal setup seems to work OK https://stackblitz.com/edit/apollo-basic-fed-demo-twdpoe?file=package.json, though I realize that's probably not very helpful since it's not upgrading from a previous version.

**Comment by marcelkottmann** [comment]
Hi @benweatherman ,

I have no lines in the stack trace but I guess its 

node_modules/@apollo/gateway/dist/executeQueryPlan.js:4 because there is this line

    const node_fetch_1 = require("node-fetch");

So basically you are using node-fetch in your code, without declaring it as a production dependency.

We use `npm` and these are apollo-related top level project package.json in the `dependencies section`:
```json
    "@apollo/gateway": "2.0.5",
    "apollo-server": "3.9.0",
    "apollo-server-cache-redis": "3.3.1",
    "apollo-server-caching": "3.3.0",
    "apollo-server-core": "3.9.0",
    "apollo-server-express": "3.9.0",
    "apollo-server-lambda": "3.9.0",
    "apollo-server-plugin-base": "3.6.1",
    "apollo-server-plugin-response-cache": "3.6.1",
    "apollo-server-types": "3.6.1",
    "graphql": "16.5.0",
```

Your test project you linked is not using `npm` (it is using `turbo` under the hood). If you would try that command on your project `npm ci --only=production` you might get the missing import `node-fetch` error.

**Comment by benweatherman** [comment]
Thanks for the extra info @marcelkottmann! Not sure how I missed these before but we import `node-fetch` in a few places now (e.g. https://github.com/apollographql/federation/blob/6abb0810ccd16cbdfe666ae096dc04c782c6f2ca/gateway-js/src/executeQueryPlan.ts#L5).
