### ISSUE TITLE
Decouple from opentelemetry and allow opentrace providers to have same observability

### ISSUE THREAD

**Issue by theJC** [apollographql/federation#2023]
With the [introduction of the use of OpenTelemetry a year ago](https://www.apollographql.com/blog/backend/architecture/introducing-open-telemetry-for-apollo-federation/) improved observability was provided to those using OpenTelemetry.  Unfortunately not all of your customers are using OpenTelemetry.  One of the leading observability SaaS vendors (Datadog) provided javascript instrumentation libraries is heavily tied to OpenTrace.

Can't the tracing implementation be abstracted away so that different providers can be plugged in to Gateway so that one could easily provide an implementation that leverages the tracing that the dd-trace library supports, and not be directly coupled to OpenTelemetry?

**Comment by edude03** [comment]
Datadog also supports OpenTelemetry though

**Comment by theJC** [comment]
Not their datadog apm agent though, thats still OpenTrace based.
https://github.com/DataDog/dd-trace-js

**Comment by theJC** [comment]
As of June 13, 2023 Datadog now provides (beta support) Otel span compatibility with their instrumentation library, thereby obsoleting this issue. 

https://github.com/DataDog/dd-trace-js/releases/tag/v4.2.0
