### ISSUE TITLE
Is there a way for gateway to return response before sending request to subgraph service?

### ISSUE THREAD

**Issue by namlt3820** [apollographql/federation#2064]
Hi, I'm trying to integrate authentication into my Nodejs apollo gateway. If the user doesnt have a specific header, I want to return a warning response instead of forwarding it to some underlying microservice. But from the documentation, this method only returns void
```
class AuthenticatedDataSource extends RemoteGraphQLDataSource {
  willSendRequest({ request, context }) {
    // Pass the user's id from the context to each subgraph
    // as a header called `user-id`
    request.http.headers.set('user-id', context.userId);
  }
}
```
Am I missing something? Thanks

**Comment by lennyburdette** [comment]
@namlt3820 use Apollo Server's plugin hooks for that! You can return arbitrary responses in [`responseForOperation`](https://www.apollographql.com/docs/apollo-server/integrations/plugins-event-reference#responseforoperation) (or return null to allow the operation to execute).

**Comment by namlt3820** [comment]
@lennyburdette Perfect, that's exactly what I'm looking for. Thank you.
