### ISSUE TITLE
Typescript does not compile with gateway 0.x and Apollo Server v2

### ISSUE THREAD

**Issue by smyrick** [apollographql/federation#2077]
If you use gateway version 0.29.0+ with Apollo Server v2 you will start relying on `apollo-server-types` both `^0.9.0` OR `^3.0.0`. See code 

`apollo-server-types@0.9.0` -> AS2
`apollo-server-types@3.0.0` -> AS3

https://github.com/apollographql/federation/blob/7f5565aedefa05f0453985336a24d3e3d8aebd2f/gateway-js/package.json#L41

Normally in dependencies, this would be ok, that we can use either version, however, the underlying dependency `apollo-server-env` also has a major version change. We updated the `GraphQLRequest.headers` to instead defined in `apollo-server-env` to be the `Headers` from `node-fetch`. This was an unintentional "breaking change" that got populated. It appears to have no effect on the runtime of most users but what it does break is Typescript compile steps. So if users have a `tsc` step they can't even use these versions together.

A potential fix is to instead have npm pull in the dependency of one or the other, we pull in both libs and define in the typed source code that the types themselves could be one or the other.

I believe we should also apply this fix to `main` if we want `@apollo/gateway` v2 to still work with AS2.

---------------

After this large refactoring, it will require more work to re-apply my initial PR: https://github.com/apollographql/federation/pull/2050

---------------

Initial PR to solve that now needs to be rewritten: https://github.com/apollographql/federation/pull/1964

Reproducible Stackblitz: https://stackblitz.com/edit/apolloserver-2-with-gateway-45?file=README.md

**Comment by glasser** [comment]
I think two small fixes will fix this:

- Backport https://github.com/apollographql/apollo-server/pull/5537/commits/191d4278fd08bdfda8195fda595108e01819b872 to AS2 and put out a quick apollo-server-env release
- Tweak overallCachePolicy in `@apollo/server-gateway-interface` to explicitly support either AS2 or AS3 versions (which actually simplifies the relevant code in `@apollo/gateway`)

**Comment by smyrick** [comment]
This has now been resolved with the following versions:

```json
"@apollo/gateway": "0.52.1",
"apollo-server": "2.26.0"
```

OR if you have a hard set dependency on `apollo-server-types`

```json
"@apollo/gateway": "0.52.1",
"apollo-server": "2.26.0",
"apollo-server-types": "0.10.0"
```


See the linked issues above for more details.
