### ISSUE TITLE
Support (and/or documentation) for nested `@provides` fields arg

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#213]
Currently there's neither support or documentation for a nested `@provides` `fields` argument, like so:
`@provides(fields: "parent { child }")`

In its current form, we can see composition errors by running the test introduced by this commit:
https://github.com/apollographql/federation/commit/cf7a8811a59040ac7e34ab152d9389385fbf781b

The validation that reports this error is not permissive enough to allow this composition to happen. Relatedly, the error being reported isn't very helpful in that it doesn't tell the user precisely what they're doing wrong or how to fix it.

Beyond just the composition errors, we would also need to validate that this actually works as intended in query planning.

Until then, documentation about this limitation would be helpful. As a heavier lift, writing a correct validation which at least informs the user of what they're trying to do and that it's unsupported would be even more helpful.

**Comment by chriskrogh** [comment]
@trevor-scheer is this feature being worked on? I noticed  https://github.com/apollographql/federation/issues/815 and https://github.com/apollographql/federation/issues/416 but I'm not sure where the source of truth is for this?

**Comment by pcmanus** [comment]
Closing this issue as this is nested provides are supported as of federation 2.0. There is even a unit test demonstrating it: https://github.com/apollographql/federation/blob/main/query-planner-js/src/__tests__/buildPlan.test.ts#L200.
