### ISSUE TITLE
Uncaught TypeError TypeError: Cannot read property 'QUERY' of undefined

### ISSUE THREAD

**Issue by lakshmajee** [apollographql/federation#2131]
## Actual behavior

When starting a gateway service built with `@apollo/gateway` and `@apollo/federation` it throws the following unrecoverable error.

![error](https://user-images.githubusercontent.com/15211916/188683221-ccb56d83-9700-493c-a2de-dd16f34e6da3.png)

You can find the `graphql`, `federation` version in below json

package.json
```json
"dependencies": {
    "graphql": "^15.8.0",
     "graphql-upload": "^16.0.2"
     "@apollo/federation": "0.20.4",
     "@apollo/gateway": "^2.1.1",
    "apollo-server": "^3.10.2",
    "apollo-server-core": "^3.10.2",
    "apollo-server-express": "^3.10.2"
}
```

## Expected behavior

Should not throw an error, it should run the service with gateway

**Comment by pcmanus** [comment]
It's hard to be 100% precise without reproduction steps, but this seem to be a dependency issue.

In particular, given that you are using the 2.x version of the gateway (here `^2.1.1`), then 2 things seems wrong here:
1. the 2.x version of the gateway depends on graphQL-js v16.6, so the dependency on `^15.8.0` is a bit fishy.
2. you should not be depending on `@apollo/federation` at all as that package does not exists with federation 2 anymore. Instead probably rely on the `@apollo/subgraph` package (with the same version than the gateway).

In any case, the stack trace of the error fairly clearly points to something wrong with the `graphql` dependency, so I suspect it's one of the 2 things above (or their combination).
