### ISSUE TITLE
Incorrect hint (and composition behavior?) for inconsistent repeatable directives

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#2134]
**Description:** When two subgraphs apply a directive to the same type or shareable field with different arguments, *and the directive is repeatable,* the hint says that it's not repeatable and only one application is emitted. 
**Reproduction:** https://stackblitz.com/edit/basic-federation-dpcqjk?file=test.js
**Version:** `@apollo/composition@2.1.1`
**Actual behavior:**

```graphql
# subgraph one
extend schema @composeDirective(name: "@auth")
directive @auth(scope: String!) repeatable on FIELD_DEFINITION
type Query {
  shared: String @shareable @auth(scope: "VIEWER")
}
```
```graphql
# subgraph 2
extend schema @composeDirective(name: "@auth")
directive @auth(scope: String!) repeatable on FIELD_DEFINITION
type Query {
  shared: String @shareable @auth(scope: "ADMIN")
}
```

```js
[
  CompositionHint {
    definition: {
      code: 'INCONSISTEN_NON_REPEATABLE_DIRECTIVE_ARGUMENTS',
      level: [Object],
      description: 'A non-repeatable directive is applied to a schema element in different subgraphs but with arguments that are different.'
    },
    message: 'Non-repeatable directive @auth is applied to "Query.shared" in multiple subgraphs but with incompatible arguments. The supergraph will use arguments {scope: "VIEWER"} (from subgraph "one"), but found arguments {scope: "ADMIN"} in subgraph "two".',
    nodes: [ /* ... */ ]
  }
]
```

**Expected behavior:** 
* The hint shouldn't call the directive "non-repeatable".
* I think composition should include both directive applications in the supergraph, but I'm not sure about that.

**Comment by clenfest** [comment]
The `@auth` directive definition above is not repeatable, but I added repeatable and it's the same, so I'm assuming that just copypasta. The reason this seems to happen is that the types are getting compared before the directives are built, so I switched the order and that seems to take care of it.

**Comment by lennyburdette** [comment]
ah yeah sorry i made the directives repeatable in the stackblitz but didn't copy it correctly for the code samples in the issue description. thanks for the fix!
