### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by mrsants** [apollographql/federation#216]
when trying to install @apollo/gateway with yarn, I have the following error:

error @apollo/gateway@0.21.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <15.0". Got "10.22.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by trevor-scheer** [comment]
This is as expected. Node 12 has been in LTS for nearly a year now, and we depend on some of its features. As such do not support `node` versions `<12.13.0` as the error suggests. You'll have to update your version of `node` in order to run the gateway.

**Comment by aim97** [comment]
Will you support higher versions of node, i'm getting the same message now using version "v16.13.2".

**Comment by yarapolana** [comment]
Getting the same error using node 18.9.1 on a deployment environment, can't change it there.

**Comment by trevor-scheer** [comment]
Current versions of the gateway (2.x) allow `">=12.13.0"` without an upper limit anymore, so this shouldn't be an issue going forward. 
https://github.com/apollographql/federation/blob/main/gateway-js/package.json#L21

**Comment by lanternlogic** [comment]
I get a similar issue when i try to `yarn install` on even just node v18, but instead for @apollo/federation, ie:
`error @apollo/federation@0.27.0: The engine "node" is incompatible with this module. Expected version ">=12.13.0 <17.0". Got "18.18.2"`
despite me certainly not using @apollo/federation anywhere... ny idea how to fix this?
I am running:
`"@apollo/server": "^4.9.5"`

**Comment by trevor-scheer** [comment]
@lanternlogic what's the output of `yarn why @apollo/federation`? Something in your project is depending on it.

**Comment by lanternlogic** [comment]
@trevor-scheer I actually figured it out.. was from an old package in another workspace within my project... i didnt know `yarn install` in one workspace checks deps in other workspaces!

**Comment by shtefanilie** [comment]
@trevor-scheer I am seeing the same issue on my end, whilst trying to use node 18.
It seems it's part of `apollo` and in turn `apollo-language-server`. 
I've updated apollo to version `2.34.0`, but it seems the `federation` package is still at version 27.

I do see this package is deprecated https://www.npmjs.com/package/@apollo/federation

Here is the output for `yarn why`

```
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@apollo/federation@0.27.0"
info Reasons this module exists
   - "_project_#PROJECT_NAME#apollo#apollo-language-server" depends on it
   - Hoisted from "_project_#PROJECT_NAME#apollo#apollo-language-server#@apollo#federation"
info Disk size without dependencies: "1.72MB"
info Disk size with unique dependencies: "2.22MB"
info Disk size with transitive dependencies: "16.46MB"
info Number of shared dependencies: 7
✨  Done in 10.17s.
```

**Comment by lanternlogic** [comment]
@shtefanilie you should update to the latest Apollo v4.x

**Comment by shtefanilie** [comment]
@lanternlogic I already did. But it was still referencing federation 27.  https://github.com/apollographql/apollo-tooling/blob/a778ca162bdd20be9e60a914887302390c274644/packages/apollo-language-server/package.json#L20

**Comment by shtefanilie** [comment]
> @shtefanilie you should update to the latest Apollo v4.x

@lanternlogic I think you're confusing [apollo-toolkit](https://github.com/apollographql/apollo-tooling) with [@apollo/client](https://www.npmjs.com/package/@apollo/client). And even in that case, both of them don't have v4.x

**Comment by jwarykowski** [comment]
Hey @shtefanilie, this was originally reported here: https://github.com/apollographql/apollo-tooling/issues/2675

You can get around this problem by setting a dependency resolution.

```json
"overrides": {
  "@apollo/federation": "0.38.1"
}
```

Its not super ideal but either way you should look at migrating to https://the-guild.dev/graphql/codegen as apollo codegen:generate is deprecated.

**Comment by ibmitw** [comment]
I have same problem. How to remove or migrate @apollo/federation@0.27.0 ? I can't migrate to node v18 because this problem.

**Comment by lanternlogic** [comment]
@ibmitw try running yarn why @apollo/federation to see where it's coming from, and then remove that package.
It turned out for me that another yarn workspace within the project was referencing @apollo/federation. That package I wasn't using anymore anyway, so I removed it and made it work.
