### ISSUE TITLE
Publish gateway with esm module compatibility 

### ISSUE THREAD

**Issue by adikari** [apollographql/federation#2226]
I am using Apollo gateway with @apollo/server package and managed gateway. When I bundle the app as esm module the server fails as there are multiple copies of graphql. One loaded as esm and another loaded as common js.

There has been a similar issue with Apollo server which has now been fixed in Apollo server v3. https://github.com/apollographql/apollo-server/issues/5627

However apollo gateway package can't yet be used with esm modules. I want to use esm modules mostly because of the top level await to load configurations for my app which would significantly improve the performance. 

With the recent update to Apollo v3 all my subgraphs work as esm module. The last piece would be to add that support in gateway.

**Comment by dobrynin** [comment]
I'd also like to see this. Right now it looks like our bundle is including a the big protobuf library twice which I _think_ is because `@apollo/subgraph` is CJS only.

**Comment by trevor-scheer** [comment]
I'm not sure if or when this change will be prioritized. In the meantime, if performance or size are a major concern for your app I strongly recommend checking out [the router](https://www.apollographql.com/docs/router/).

**Comment by dobrynin** [comment]
Thanks for the reply @trevor-scheer. I've been taking a look at router lately; do I understand correctly that self-hosting the router is enterprise-only (as opposed to Gateway which was always self-hosted)? I'd love to migrate but it looks like we'd have to re-tool everything to work w/ the router living in Apollo's infra (I also noticed that it seems like parsing JWTs in the Router is also enterprise only, which would also require some retooling compared to Gateway).

Appreciate any insight you have, I've been trying to wrap my head around all the changes w/ Federation 2 in recent days :)

**Comment by trevor-scheer** [comment]
@dobrynin sorry for the delay. Self-hosting the router is not enterprise only to my knowledge, though the JWT handling is as you've mentioned.

**Comment by dobrynin** [comment]
I chatted w/ support a bit ago and the impression that I got was that legacy customers were able to continue self-hosting and parsing JWT tokens, but I've yet to try it out myself. Anyway I know that's not the subject of this issue so I'll bring my questions elsewhere if we hit more roadblocks. Thanks again!
