### ISSUE TITLE
Lack of __resolveReference error handling/fallback

### ISSUE THREAD

**Issue by leeroyrose** [apollographql/federation#2289]
## Environment
Runtime: Node 16
Package Manager: Yarn
@apollo/federation Version: 0.38.1
@apollo/subgraph Version: 2.2.1
Working recreation: https://github.com/leeroyrose/federation

## The Problem
Using Federation to build a system that can search entities across multiple subgraphs, it's become apparent that when an entity cannot be resolved, the entire response returns null and it's not possible to provide meaningful feedback or take action to prevent it.

Running the application linked above will start a Gateway and a Search, Car and Article subgraph. the search subgraph holds loose references to what is available on the other subgaphs (id and type). The type is used to feed the `resolveType` fn on the `SearchResult` union. The id is then used to resolve the entity from the respective subgraph. The search system, on a good day, works like this:

```graphql
query HappySearch {
  search(term: "") {
    ... on SearchError {
      message
    }
    ... on SearchSuccess {
      total
      items {
        __typename
        ... on Car {
          id
          manufacturer
          model
        }
        ... on Article {
          body
        }
      }
    }
  }
}
```

And can resolve rich results from multiple subgraphs

```json
{
  "data": {
    "search": {
      "total": 4,
      "items": [
        {
          "__typename": "Car",
          "id": "car-1",
          "manufacturer": "Audi",
          "model": "R8"
        },
        {
          "__typename": "Car",
          "id": "car-2",
          "manufacturer": "Porsche",
          "model": "911"
        },
        {
          "__typename": "Article",
          "id": "article-1",
          "body": "..."
        },
        {
          "__typename": "Article",
          "id": "article-2",
          "body": "..."
        }
      ]
    }
  }
}
```

When search holds reference to an entity that may no longer exist (term changed to "sad" to load fixtures with stale references):

```graphql
query SadSearch {
  search(term: "sad") {
    ... on SearchError {
      message
    }
    ... on SearchSuccess {
      total
      items {
        __typename
        ... on Car {
          id
          manufacturer
          model
        }
        ... on Article {
          body
        }
      }
    }
  }
}
```

The response is:

```json
{
  "data": null
}
```

The `_entities` call to the subgraph produces these results:

```graphql
query ($representations: [_Any!]!) {
  _entities(representations: $representations) {
    __typename
    ... on Article {
      id
    }
  }
}
```

With:

```json
{
  "representations": [
    {
      "__typename": "Article",
      "id": "article-1"
    },
    {
      "__typename": "Article",
      "id": "article-2"
    },
    {
      "__typename": "Article",
      "id": "article-6"
    }        
  ]
}
```
Where article 6 is purposely not defined:

```json
{
  "data": {
    "_entities": [
      {
        "__typename": "Article",
        "id": "article-1"
      },
      {
        "__typename": "Article",
        "id": "article-2"
      },
      null
    ]
  }
}
```

## Expectation
I understand that returning a null result would void the contract but it feels quite drastic to just null the whole response out.

Changing the `items` type to allow the search result to be nullable does somewhat alleviate the issue:

```graphql
type SearchSuccess {
    total: Int!
    # from
    items: [SearchResult!]!
    # to
    items: [SearchResult]!
}
```

Now, we get the full list, with `null` in place of the failed entities. This is a step, and we can handle the errors, but we can't tell which entity failed, nor it's id or why it failed. Feels like there should be another way.

## Proposal
What I would like to do is be able to fallback to another entity when an entity is not found. This would allow for the full list of results to still come back and a way for consumers to handle those cases where an entity was not resolved.

It would be nice to have the flexibility to do either one of two things:

- Allow `__resolveReference` to operate on a union type in the subgraph. This would mean unions would have to support the `@key` directive. Equally the union could be swapped for an interface that supports `@key` and supports `__resolveReference`.

Though verbose this allows the most flexibility:

```typescript
const resolvers = {
    CarResponse: {
        __resolveReference: async (_, {id}) => {
            const car = await findCar(id);

            if (!car) {
                return {
                    __typename: 'CarNotFound',
                    id,
                    message: 'No longer exists'
                }
            }

            return {
                ...car,
                __typename: 'Car',
            }
        }
    }
}
```

```graphql
query PerfectSearch {
  search(term: "") {
    ... on SearchError {
      message
    }
    ... on SearchSuccess {
      total
      items {
        __typename
        ... on CarResponse {
            __typename
            ... on Car {
                id
                model
            }
            ... on CarNotFound {
                id
                message
            }
        }
        ... on ArticleResponse {
            __typename
            ... on Article {
                id
                body
            }
            ... on ArticleNotFound {
                id
                message
            }
        }
      }
    }
  }
}
```

- Allow via some means, a way to examine the `_entities` response and return a fallback entity in it's place, as per the example, I could intercept all `null` and replace them with:

```json
{
    "__typename": "SearchResultNotFound",
    "reason": "Entity Car with id 'car-1' was not found"
}
```

```graphql
query BetterSearch {
  search(term: "") {
    ... on SearchError {
      message
    }
    ... on SearchSuccess {
      total
      items {
        __typename
        ... on SearchResultNotFound {
            id
            reason
        }
        ... on Car {
          id
          manufacturer
          model
        }
        ... on Article {
          body
        }
      }
    }
  }
}
```

I prefer option one because of the separation of concerns. Subgraphs can manage their own errors.

Hope this makes sense! I've used this search system as an example but it could apply to any instance where a list of federated entities are being resolved.

**Comment by pcmanus** [comment]
The changes from #2277 (which has a PR in review that you're welcome to test if you're not afraid of testing it from source) will essentially allow you to implement that 1st option (because it essentially introduces `__resolveReference` for interfaces, which is what that 1st option essentially does with `CarResponse` if it is an interface).

Essentially, your "car" subgraph will be able to define a `CarResponse` interface (with just `id`) and its `Car` and `CarNoFound` implementations, and a `CarResponse.__resolveReference` that is exactly what you mention above. Your "search" subgraph can then simply declare `CarResponse` as an `@interfaceObject` and don't have to worry about the details of that that can be.

**Comment by leeroyrose** [comment]
Hey! Thank you for the quick response. I did spend some time reading that pr and figured it would have some relevance to this. I'll try to find some time today to test this out and will report back. 😄
