### ISSUE TITLE
Expose ApolloGateway's queryPlanStore to client

### ISSUE THREAD

**Issue by AneethAnand** [apollographql/federation#2308]
## Description
Based on the understanding of the Apollo federation library source code, it seems that the queryPlanStore (LRUCache<string, QueryPlan>) size is configurable by the client, but the Cache object itself is not configurable. 

```javascript
    this.queryPlanStore = this.initQueryPlanStore(
      config?.experimental_approximateQueryPlanStoreMiB,
    );
```

## Issue
Since the cache is not configurable, we cannot initiate our own cache or even support Redis cache. 

## Possible Impact
By allowing the clients to add their own cache,  helps them add metrics for tracking hit rates of these caches.

## Solution
Add a cache option to "QueryPlannerConfig", clients could use them to add their implementation of LRUCache.

```javascript
export type QueryPlannerConfig = {
   ......
  incrementalDelivery?: {
    enableDefer?: boolean,
  }
  cache?: LRUCache<string, QueryPlan>,
}
```

**Comment by korinne** [comment]
Thanks for raising this issue, and for opening a PR! Our team has filed this under review, and will provide feedback shortly.

**Comment by korinne** [comment]
As your PR was approved and merged (congrats!), I'll be closing this issue. Thanks again for your contribution!
