### ISSUE TITLE
chore(stargate): Enable container publishing via script

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#234]
Currently we're using a GH action to publish the `stargate` container on release.
https://github.com/apollographql/federation/blob/main/.github/workflows/publish.yml#L18

Unfortunately, this doesn't provide us with an easy path to publishing locally when needed, nor is it portable to another CI platform like Circle.

ref: https://github.com/apollographql/federation/pull/197#pullrequestreview-501004673

**Comment by pcmanus** [comment]
Closing as outdated (stargate has been removed).
