### ISSUE TITLE
Can not use @link with "@apollo/subgraph": "^2.2.3"

### ISSUE THREAD

**Issue by paulbijancoch** [apollographql/federation#2344]
## Expected behavior
I wanted to convert my schema to federation 2 and import the @inaccessible-direktive by loading it with the `extend schema @link(url: "https://specs.apollo.dev/federation/v2.0", import: ["@key", "@shareable", "@inaccessible"])` in our schema.

## Actual behavior
Unfortunately, the `buildSubgraphSchema` ends in a `GraphQLSchemaValidationError: Unknown directive "@link".`

Is there anything I am missing?

We appreciate your help!

**Comment by korinne** [comment]
Thanks for raising this issue! Could you provide a repo so we can reproduce this problem?

**Comment by paulbijancoch** [comment]
I have found the error: We were using the `import { gql } from 'graphql-tag';` instead of the `import { parse } from 'graphql';` function. That raised the error.

Thank you for your help :-)
