### ISSUE TITLE
misleading composition hints when using `@interfaceObject`

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation#2397]
Given a simple schema

```graphql
// subgraph A
interface Inventory @key(fields: "id") {
  id: ID!
  products: [Product!]!
}

type OpenSourceInventory implements Inventory @key(fields: "id") {
  id: ID!
  products: [Product!]!
}

// subgraph B
type Inventory @interfaceObject @key(fields: "id") {
  id: ID!
  deprecatedProducts: [DeprecatedProduct!]!
}
```

We are getting misleading composition hints:

```
rover HINT: [INCONSISTENT_INTERFACE_VALUE_TYPE_FIELD]: Field "Inventory.products" of interface type "Inventory" is defined in some but not all subgraphs that define "Inventory": "Inventory.products" is defined in subgraph "inventory" but not in subgraph "products".
rover HINT: [INCONSISTENT_INTERFACE_VALUE_TYPE_FIELD]: Field "Inventory.deprecatedProducts" of interface type "Inventory" is defined in some but not all subgraphs that define "Inventory": "Inventory.deprecatedProducts" is defined in subgraph "products" but not in subgraph "inventory".
```

It looks like the hints are unaware that `Inventory` interface is an entity so the differences in fields are expected.

---
Repro available in [apollographql/apollo-federation-subgraph-compatibility](https://github.com/apollographql/apollo-federation-subgraph-compatibility) repo (`apollo-server` and `federation-jvm` implementations were updated to v2.3 tests).

To run tests, execute following make target from root dir:
```
make test subgraph=apollo-server
```

**Comment by atomheartother** [comment]
Oh hey, I actually reported this yesterday in rover!

https://github.com/apollographql/rover/issues/1511

**Comment by pcmanus** [comment]
@sachindshinde: noticed you were set as assignee, so hope you don't mind, but took the liberty to create a quick PR for this (#2412) since I was looking at this, it's fairly trivial to fix, and it's ultimately my fault for forgetting to update this in the `@interfaceObject` PR. Maybe I can entice you to review ? :)

**Comment by sachindshinde** [comment]
@pcmanus No worries there, thanks for the quick fix! I'm down to review 🙂
