### ISSUE TITLE
Subgraph resolver is not attaching subscription resolver to the subscription type.

### ISSUE THREAD

**Issue by sushilkjaiswar** [apollographql/federation#2407]
### Description
I am working on a Nestjs graphql(Schema First) api project in which I want to add subscription feature for attaching realtime communication between client and api server. This is a federation server with apollo's subgraph module to build the final graphql schema. All other features are working fine except Subscription feature when using apollo/subgraph. 

```
Yarn : 1.22.19
Modules details,
    @apollo/subgraph": "^2.3.2"
    @nestjs/common": "^9.0.0"
    @nestjs/core": "^9.0.0"
    @nestjs/graphql": "^10.2.0"
    @nestjs/mercurius": "10.2.0"
    @nestjs/platform-express": "^9.3.9"
    @nestjs/platform-fastify": "^9.3.9"
    graphql": "^16.6.0"
    mercurius": "^11.0.0"
```

### Expected Behaviour

Adding a Subscription type should work as per Graphql specficiation. Doubt if the specification is also applicable to federation apis.

### Actual Behaviour

The actuall behaviour is that the websocket connection drops with the following message when the subscription query is used in the graphiql editor in the browser.

`Subscription field must return Async Iterable. Received: undefined.`

### My Investigation
After digging, I found that the above error occurs when there is no subscribe field attached to the subscription type field defined in the  resolver which starts listening. Unable to find any clue from search engine about the issue, I started debugging the code and found that apollo/subgraph module version 2.3.2 doesn't process subscription field in the following file `buildSchemaFromSdl.ts` and the function name is `addResolversToSchema`. 

I was unable to get more info from apollo stackoverflow queries or from the issues reported excepted one issue reported regarding detail specifictaion for Subscription feature for 3.x.x versions.

### What is the relat status of this feature
After my learning I can reach to conclusion that this feature is intentaionally not a part of the current module. Let me know if my understanding is incorrect. 

Is this fetaure planned for future, if so when is this planned and expected to be part of the module?

**Comment by trevor-scheer** [comment]
Fixed by https://github.com/apollographql/federation/pull/2388 (we'll be releasing in a patch tomorrow)
