### ISSUE TITLE
@shareable inputs now allowed for federated subgraph

### ISSUE THREAD

**Issue by joshfoeh** [apollographql/federation#2511]
### Issue Description

Rover CLI throws an error when I attempt to check a subgraph that has an `input` object that is marked with the `@shareable` directive.

schema.graphqls:
```
extend schema
    @link(
        url: "https://specs.apollo.dev/federation/v2.0"
        import: ["@shareable"]
    )

type Query {
    fetchList(options: ListPagination): [String!]!
}

input ListPagination @shareable {
    start: Int
    pageSize: Int
}
```

Command:
`rover subgraph check SUPERGRAPH@production --schema schema.graphqls --name subgraph_name`

Error:
`INVALID_GRAPHQL: [subgraph_name] Directive "@shareable" may not be used on INPUT_OBJECT.`

Rover CLI version: v0.10.0

I believe this should be a valid use case (a shareable input type) as we have multiple subgraphs using this same input type.

### Link to Reproduction

N/A

**Comment by trevor-scheer** [comment]
Shareable is more concerned with the _resolution_ of fields (allowing a field to be resolved by multiple subgraphs). If you're just looking to define and use common input types in multiple subgraphs, you can already do that [using value types](https://www.apollographql.com/docs/federation/federated-types/sharing-types/#input-types).
