### ISSUE TITLE
Apollo Federation - How to share customized types between services, except scalar types and enum

### ISSUE THREAD

**Issue by CaroseKYS** [apollographql/federation#2571]
I have two services, there are some types and inputs to share：
* Service A
```
input Page {
  limit: Int
  offset: Int
}
type PageInfo {
  page: Int
  page_size: Int
}
```

* Service B
```
input Page {
  limit: Int
  offset: Int
}
type PageInfo {
  page: Int
  page_size: Int
}
```
When i federate them use `apollo-gateway`, i got errors like:
`There can be only one type named "Page".`,`There can be only one type named "PageInfo".`

What can i do? Is this method is wrong?

**Comment by trevor-scheer** [comment]
For anyone who's still interested in this and hasn't kept up with the changes, I encourage you to check out the changes that came with Federation 2.0+. I suspect all of the concerns in here have been resolved, but if not please open a specific issue in the federation repo for the functionality you're looking for.
