### ISSUE TITLE
Partial responses not always working correctly (data is missing from gateway response).

### ISSUE THREAD

**Issue by Glen-Moonpig** [apollographql/federation#260]
@apollo/gateway 0.21.0
@apollo/federation 0.20.4

### Expected behaviour

When a GraphQL operation requires the gateway to send HTTP requests out to multiple services and 1 reaches a timeout then we should receive the data from service that did not reach timeout.

### Actual behaviour

When a GraphQL operation requires the gateway to send HTTP requests out to multiple services and 1 reaches a timeout then we are sometimes not receiving the expected partial response data.

For example, I have tested a query that resolves data from 2 services (lets calls them test1 and test2).

The query being sent is:
```
{
  info {
    text
  }
  version
}
```
info is an object resolved from test1 and version is a string resolved from test2.

When I lower the HTTP timeout for test2 then I get a response like this

```json
{
  "errors": [
    {
      "message": "Request to test2 failed. Message: network timeout at: https://api.test2.com/graphql. Type: request-timeout",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Request to test2 failed. Message: network timeout at: https://api.test2.com/graphql. Type: request-timeout",
            "    at /var/task/fetch.js:39:23",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

BUT when I instead lower the timeout for test2 to force a timeout scenario then I do get some data

```
{
  "errors": [
    {
      "message": "Request to test1 failed. Message: network timeout at: https://api.test1.com/graphql. Type: request-timeout",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Request to test1 failed. Message: network timeout at: https://api.test1.com/graphql. Type: request-timeout",
            "    at /var/task/fetch.js:39:23",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "info": null,
    "version": "v2.11.0"
  }
}
```

I think this is either due to a race condition or the difference in version being a string and info is an object.

**Comment by Glen-Moonpig** [comment]
I have several services federated by the gateway. A timeout from one of them results in a response with data from the others, but a timeout on any other service results in no data from any. I can't figure out why this happens, there must be something different in how the execution plan works.

**Comment by Glen-Moonpig** [comment]
OK I think I may have figured it out. If the query that failed fetch returns a nullable type then I get partial data from the other queries in the operation. If the query that failed fetch returns a non-nullable type then response contains:
```
data: null
```
Is this correct behaviour??

**Comment by Enrico2** [comment]
@Glen-Moonpig That sounds correct! According to the spec, it seems to be behaving as expected:
https://spec.graphql.org/June2018/#sec-Errors-and-Non-Nullability

**Comment by Glen-Moonpig** [comment]
Ok thanks. I think we probably just have a badly designed schema that does not allow for partial responses.
