### ISSUE TITLE
ReUse Fragment not effectively reusing the fragments in the Query

### ISSUE THREAD

**Issue by AneethAnand** [apollographql/federation#2613]
### Issue Description

ReUsing fragment is not effectively reusing in the following scenarios

- I have added a test case in operation.test in the following PR
    https://github.com/apollographql/federation/pull/2612#issue-1737571378
   to show how the following expansion in the method "diffWithNamedFragmentIfContained"
<img width="863" alt="image" src="https://github.com/apollographql/federation/assets/43860019/64a075d7-6bc7-49ed-a9e8-742d0097eaa2">

```
let updatedThis = this.expandFragments([candidate.name], this.fragments);
```

causing the Query Plan to look like
```
  fragment OnSubT2 on T2 {
    x
    y
    u
    t
    s
    r
    q
    p
  }

  {
    t {
      d {
        ...OnSubT2
        z
        w {
          d {
            x
            y
            u
            t
            s
            r
            q
            p
            v
          }
        }
      }
    }
    duplicate: t {
      d {
        ...OnSubT2
        z
        w {
          d {
            x
            y
            u
            t
            s
            r
            q
            p
            v
          }
        }
      }
    }
  }`
```

instead of 
```
    fragment OnSubT2 on T2 {
      x
      y
      u
      t
      s
      r
      q
      p
    }

      t {
        d {
          ...OnSubT2
          z
          w {
            d {
              ...OnSubT2
              v
            }
          }
        }
      }
      duplicate: t {
        d {
          ...OnSubT2
          z
          w {
            d {
              ...OnSubT2
              v
            }
          }
        }
      }
  `)
```

### Link to Reproduction

https://github.com/apollographql/federation/pull/2612#issue-1737571378

### Reproduction Steps

Run the test case added in the operation.test.ts

**Comment by pcmanus** [comment]
As mentioned on the PR, this is fixed on the last released version, 2.4.7.
