### ISSUE TITLE
Build _Entity query dinamically

### ISSUE THREAD

**Issue by rhdeandrade** [apollographql/federation#2646]
We're using apollo rover to compose our super graph and running it via Apollo Gateway Express. However it's not generating automatically te _Entity union with all Entities with @key in it. Is there any documentation on how to create this dynamically when composing the supergraph?

**Comment by EverlastingBugstopper** [comment]
Hi @rhdeandrade - I've transferred this issue to the `federation` repository where they may be able to help you better.

**Comment by trevor-scheer** [comment]
That's correct.
