### ISSUE TITLE
OTEL error "Can not execute the operation on ended Span"

### ISSUE THREAD

**Issue by velias** [apollographql/federation#2652]
### Issue Description

If subgraph call fails with http error (eg. 400), then there is error `Can not execute the operation on ended Span {traceId: 496674e5d6add505f18b5cdcb6259322, spanId: e9285ed17413b036}` in the app log from `otel` module. SpanId in the message is from `gateway.postprocessing` span. Looks like some error/result reporting doesn't work correctly for this Span.

### Link to Reproduction

https://github.com/velias/apollographql-federation-issue-2652-reproducer

### Reproduction Steps

* setup logging from otel
* execute query on gateway which produces http error in subgraph
* look into gateway log file

**Comment by trevor-scheer** [comment]
Hey @velias, this isn't a trivial reproduction. Please share a repository I can clone which demonstrates the issue without any creativity on my part with any necessary steps I need to take to trigger the error.

**Comment by velias** [comment]
OK, but I'm leaving for holiday later this week, not sure if I'll be able to provide it before. So be patient please.

**Comment by velias** [comment]
OK, was able to do it today, reproducer is here https://github.com/velias/apollographql-federation-issue-2652-reproducer
Instructions in README.md

**Comment by trevor-scheer** [comment]
Thanks @velias! Hoping to get a look at this tomorrow.

**Comment by velias** [comment]
Thanks for the patch
