### ISSUE TITLE
Query Plan selects most efficient `@key` instead of most specific `@key` for entity resolution

### ISSUE THREAD

**Issue by rhino88** [apollographql/federation#2695]
### Issue Description

In a scenario where a query plan could be supported by multiple keys, the generated query plan seems to choose the most efficient `@key` (fewer fields) vs. the most specific (more fields) when multiple `@key`s are available.

*Subgraph A*
```
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key"])

extend type Query {
  getFoo: Foo
}

type Foo {
  bar: Bar
}

type Bar @key(fields: "key1 key2 key3") {
  key1: String!
  key2: String!
  key3: String
}

```

*Subgraph B*
```
extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key"])

type Bar @key(fields: "key1 key2") @key(fields: "key1 key2 key3") {
  key1: String!
  key2: String!
  key3: String
  nonKeyField: String!
}
```

*Query*
```
query FooBar {
  getFoo {
    bar {
      nonKeyField
    }
  }
}
```

*Query Plan*
```
QueryPlan {
  Sequence {
    Fetch(service: "foo_subgraph") {
      {
        getFoo {
          bar {
            __typename
            key1
            key2
          }
        }
      }
    },
    Flatten(path: "getFoo.bar") {
      Fetch(service: "bar_subgraph") {
        {
          ... on Bar {
            __typename
            key1
            key2
          }
        } =>
        {
          ... on Bar {
            nonKeyField
          }
        }
      },
    },
  },
}
```

In the above scenario, the query plan is using `@key(fields: "key1 key2")` instead of what is likely the more specific `@key(fields: "key1 key2 key3")`.

This can pose challenges for incremental evolution of a graph where new fields are added to an entity to improve specificity or otherwise evolve an entity which may require a new set of `@key` fields while maintaining backwards compatibility with the old `@key`.

**Solution Ideas**

Could the query plan select the first `@key` in Subgraph B compatible with Subgraph A? This would better support the incremental evolution of keys and deprecation of old keys.

For example, to declare preference for the 3 field key, we would change the ordering of the `@key`s in Subgraph B like so:

`@key(fields: "key1 key2") @key(fields: "key1 key2 key3")` -> `@key(fields: "key1 key2 key3") @key(fields: "key1 key2") `

### Link to Reproduction

N/A

### Reproduction Steps

N/A

**Comment by dariuszkuc** [comment]
Hello 👋 
`@key` field set represents a selection set that allows you to uniquely identify given entity. If you already have `@key("x1 x2")` it means that you only need those 2 fields to uniquely identify the identity, i.e. if you add another field to the selection set `x3` then it would be redundant as you should be able to identify your entity just by using `x1` and `x2`.

You definitely can introduce new unique identifiers (i.e. have multiple `@key`) definitions but each selection set should uniquely identify the entity. Query planner already does the cost optimization to ensure it selects the most efficient query to resolve the request so it will pick appropriate `@key`.

Thanks,
Derek

**Comment by rhino88** [comment]
I understand the nature of `@key` and the implications associated with unique indentification. The challenge here is that the implementation does not currently support evolution of an entity over time.

For example, if I start with the following:
```type Bar @key(fields: "key1 key2") {
  key1: String!
  key2: String!
  nonKeyField: String!
}

And later new fields are added so that I now have a new field which belongs in the `@key`:

```
type Bar @key(fields: "key1 key2") @key(fields: "key1 key2 key3") {
  key1: String!
  key2: String!
  key3: String
  nonKeyField: String!
}
```

The `@key` with three fields will never get used in _any_ situation. If this is not going to be supported, this is fine...but I think there needs to be a schema check added for a `@key` that would be ignored, with a warning that the schema designer will need to create a new entity instead.

**Comment by dariuszkuc** [comment]
```graphql
type Bar @key(fields: "key1 key2") @key(fields: "key1 key2 key3") {
   key1: String!
   key2: String!
   key3: String
   nonKeyField: String!
}
```

Underlying problem with the above is that you are specifying that `key1` and `key2` are enough to uniquely select the entity so why would I need to pass the `key3` which is redundant? Your entities can have multiple `@key`s and they can vary across subgraphs so most likely what you are looking for is

```graphql
// subgraph A
type Bar @key(fields: "key1 key2") {
   key1: String!
   key2: String!
   nonKeyField: String!
}

// subgraph B
type Bar @key(fields: "key1 key2") @key(fields: "key1 key2 key3") {
   key1: String!
   key2: String!
   key3: String
   otherField: Int!
}
```

Above is valid as long as there exists some query paths that can resolve those selection sets (i.e. you cannot go from subgraph A to resolve `otherField` from subgraph B as we don't have `key3` but it is perfectly fine to resolve  `nonKeyField` if starting from subgraph B)

**Comment by rhino88** [comment]
It sounds like if a `@key` needs to evolve by adding another `field` to an existing `@key` then a new entity needs to be created. Is that expected/desired behavior?

Refocusing the discussion on this point:

> The @key with three fields will never get used in any situation.

Since this is the case, should we provide a warning at composition time that the `@key` is never used?

**Comment by dariuszkuc** [comment]
> It sounds like if a @key needs to evolve by adding another @key field to an existing @key selection set then a new entity needs to be created. Is that expected/desired behavior?

Doesn't have to be new entity (i.e. your logic may decide to ignore new identifiers, it is your implementation detail) but when evolving the type you should drop the old `@key` definitions and only include the one with additional fields.

Created https://github.com/apollographql/federation/issues/2702 for extra composition warning.

**Comment by rhino88** [comment]
Thanks for opening the feature request :pray: :smile: . That should hopefully help us and others avoid scenarios like we find ourselves in today which will be challenging to untangle across many different subgraphs. This is likely an uncommon use case, where I think we made some mistakes in defining keys along the way and are trying to evolve them in a backwards-compatible way.

> Doesn't have to be new entity (i.e. your logic may decide to ignore new identifiers, it is your implementation detail) 

I'm still not sure I follow this part about this being our implementation detail, since the query plan never provides an opportunity for our subgraph implementation details to receive the new identifier. Would it be possible to elaborate on this?

**Comment by dariuszkuc** [comment]
What I meant is -> given an existing type

```graphql
type Bar @key(fields: "key1 key2") {
   key1: String!
   key2: String!
   nonKeyField: String!
}
```

You can add new optional (or not) `key3` field to it and include it in the `@key` selection set

```graphql
type Bar @key(fields: "key1 key2 key3") {
   key1: String!
   key2: String!
   key3: String
   nonKeyField: String!
}
```

You then simply modify your `_entities` resolver to account for new value in representation, i.e. some entities may only have `key1+key2` available and others may have `key1+key2+key3` -> this is implementation detail of your `_entities` resolver.

The difference is -> if you have both `@key(key1 + key2)` and `@key(key1 + key2 + key3)` then query planner always pick the first one due to the reasons mentioned above. When you add new field and update entity `@key` then query planner will only see the updated `@key` and it always have to use 3 keys when accessing this subgraph entity.

**Comment by rhino88** [comment]
I updated some of the potential solutions above, to include a suggestion for allowing a `@key` to be deprecated e.g. `@key(fields: "...", deprecated: true)`. This would allow for schema designers to provide a hint to the query planner that a deprecated key should only be used if a non-deprecated key is unavailable. 

I think there might be a related issue to key deprecation somewhere, but I wasn't able to find it.

**Comment by smyrick** [comment]
I will comment that for a migration I can imagine this scenario

Current I have two subgraphs and they use `Foo.x` to identify the key
```graphql
// Subgraph 1
type Foo @key(fields: "x") {
  x: ID!
  someField: String
}

// Subgraph 2
type Foo @key(fields: "x") {
  x: ID!
  otherField: String
}
```

Some time in the future, I now want to migrate from using just `Foo.x` as the id to `Foo.x` AND `Foo.y`. However current subgraphs are still using only `Foo.x` as the reference. Well we can't break those subgraphs so we need to add the new key to one subgraph that understands that

This is still valid
```graphql
// Subgraph 1
type Foo @key(fields: "x") @key(fields: "x y") {
  x: ID!
  y: ID!
  someField: String
}

// Subgraph 2
type Foo @key(fields: "x") {
  x: ID!
  otherField: String
}
```

Now, if I understand correctly, you want some way in the tooling that you can indicate to all subgraphs that they need update their key references from `@key(fields: "x")` to `@key(fields: "x y")`. If all subgraphs do that then we can successfully remove `@key(fields: "x")` entirely and only use the new x + y id.

This is also still valid
```graphql
// Subgraph 1
type Foo @key(fields: "x") @key(fields: "x y") {
  x: ID!
  y: ID!
  someField: String
}

// Subgraph 2
type Foo @key(fields: "x y") {
  x: ID!
  y: ID!
  otherField: String
}
```

Today, that would have to be solved with communication, but I like the idea of adding a optional `@key.deprecated` flag so we could inform other subgraph authors with linter rules

Eventual state we want

```graphql
// Subgraph 1
type Foo @key(fields: "x y") {
  x: ID!
  y: ID!
  someField: String
}

// Subgraph 2
type Foo @key(fields: "x y") {
  x: ID!
  y: ID!
  otherField: String
}
```

**Comment by rhino88** [comment]
👍 for a `@key` deprecation argument. I think that seems like the most straightforward solution and that would be a huge for us.

We are currently trying to migrate 12+ subgraphs using an old, single value `@key(fields: "x")` to a new multi-field key (e.g. `@key(fields: "x y")`. The query plan continues to exclusively use the old single field `@key(fields: "x")` until _every_ subgraph has migrated to the new key.

The coordination has been a challenge, to say the least 😅

**Comment by gwardwell** [comment]
I don't think this issue should be closed. the problem (Router not honoring a more specific key) is _still_ a problem ([comment here](https://github.com/apollographql/federation/issues/2695#issuecomment-1692575566)).

Whether or not there is flexibility in keys, we need a way to say to both people _and_ Router "stop using X key and use Y key instead."
