### ISSUE TITLE
Use SPDX license identifiers in package.json

### ISSUE THREAD

**Issue by jayay** [apollographql/federation#2736]
Hi! I would like to advertise the usage of [SPDX license identifiers](https://spdx.org/licenses/) in this repository's `package.json` files. In my company, we use the `license` field in `package.json` files for automatic compliance checks. It would be of great advantage to not have to manually allow `@apollo/*` packages because the current value `"SEE LICENSE IN ./LICENSE"` is fragile for tooling. I am sure we're not alone with this issue.

Thanks

**Comment by trevor-scheer** [comment]
Fixed via #2741, slated for next minor release

**Comment by jayay** [comment]
Thank you so much!
