### ISSUE TITLE
Aliased field is nullified

### ISSUE THREAD

**Issue by id-ilych** [apollographql/federation#2770]
### Issue Description

Hello :wave:

It seems that aliased field is nullified in the response in certain case while working in other more-or-less equivalent cases.

### Link to Reproduction

https://codesandbox.io/p/sandbox/optimistic-frog-2qghvw

### Reproduction Steps

The query
```graphql
query {
  doesntWork: node(id: "m") {
    ...MovieFragmentAliased
    ...BookFragment
  }
  works1: node(id: "b") {
    ...MovieFragmentAliased
    ...BookFragment
  }
  works2: node(id: "m") {
    ...MovieFragmentAliased
    # ...BookFragment
  }
  works3: node(id: "m") {
    ...MovieFragmentAsIs
    ...BookFragment
  }
}

fragment MovieFragmentAliased on Movie {
  author: authorV2 { fullName }
}

fragment MovieFragmentAsIs on Movie {
  authorV2 { fullName }
}

fragment BookFragment on Book {
  author { fullName }
}
```

The response:
```json
{
  "data": {
    "doesntWork": {
      "author": null
    },
    "works1": {
      "author": {
        "fullName": "John Ronald Reuel Tolkien"
      }
    },
    "works2": {
      "author": {
        "fullName": "Luc Besson"
      }
    },
    "works3": {
      "authorV2": {
        "fullName": "Luc Besson"
      }
    }
  }
}
```

`works1` is the same as broken case but with the type that doesn't need aliasing (has a "good" field name).
`works2` is the same as broken case but with commented out alternative fragment (but why commenting something out adds data to the response?)
`works3` is the same as broken case but without aliasing.

**Comment by dariuszkuc** [comment]
Fixed in #2776
