### ISSUE TITLE
Allow implementing an interface defined in different subgraphs using different names and having multiple implementations in the same subgraph

### ISSUE THREAD

**Issue by DDDKnightmare** [apollographql/federation#2827]
This issue proposes the addition of an argument to `@interfaceObject` in order to allow implementing the same interface multiple times in the same subgraph.

--------------------

## Motivation: 
In order to avoid implementing multiple queries in each service to read data from different types, I have a `node` query, that receives a `global ID` that contains information about the type and the object's real id, so I can use it along with federation to easily read data from multiple types by using `__resolveReference`.
Update:
- Allows multiple implementations of an interface defined in a different service
- Allows us to `hint` the query planner as to which type it should resolve to
  - e.g.: 
```typescript
  const typeNameFromObject = (obj, context, info) => {
    // validate and decode globalId
    return typename;
  };
  const  myInterfaceResolvers = {
    __interfaceTypeHint: (obj, context, info) => {
      return typeNameFromObject(obj, context, info);
    }
  }
```

--------------------

desired usage example:

- node service subgraph:

```gql
interface Node @key(fields: "id") {
  ID!
}

type Query {
  node(id: ID!): Node
}
```

- other service subtraph:

```gql
type Video @key(fields: "id") @interfaceObject(interface: "Node") {
  id: ID!
  # other fields
}

type Book @key(fields: "id") @interfaceObject(interface: "Node") {
  id: ID!
  # other fields
}

```

With the current `@interfaceObject` implementation, I'd be limited to the following, if both `Video` and `Book` were handled by the same service:
```gql
type Node @key(fields: "id") @interfaceObject {
  id: ID!
  # Book fields
  # Video fields
}
```

And, if both had some common fields, but were handled by different services, I wouldn't be able to know which one would be called to resolve the field.
e.g.:

- Book service
```gql
type Node @key(fields: "id") @interfaceObject {
  id: ID!
  name: String!
  # book fields
}
```

- Video service
```gql
type Node @key(fields: "id") @interfaceObject {
  id: ID!
  name: String!
  # video fields
}
```

- query
```gql
query Node(id: ID!){
  id
  name
}
```

The above query could hand me any of the following, if called with a `Book` global ID:
- `null`, if `name` is resolved by `Video` service
- `id: <id> name: <name>`, if name is resolved by `Book` service

-----------------------

As a workaround, I'm currently using the discouraged approach to have `node` service know every type that implements it:

- node service
```gql
interface Node {
  id: ID!
}

type query {
  node(id: ID!): Node
}

extend type Book implements Node @key(fields: "id"){
  id: ID!
}

extend type Video implements Node @key(fields: "id"){
  id: ID!
}
```

**Comment by dariuszkuc** [comment]
Hello 👋 
It looks like you misunderstood the intent behind `@interfaceObject` ([docs](https://www.apollographql.com/docs/federation/federated-types/interfaces)) - it allows to extend your interfaces across federated subgraphs by adding new common fields to ALL implementations. It is not about adding new interface implementations across subgraphs. You still need one place that defines the interface and its implementations (i.e. your "workaround") but then you can extend the interface generically OR you can extend types individually.
