### ISSUE TITLE
chore(infra): Fix publishing step for `@apollo/query-planner-wasm`

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#290]
Due to a [restructure of the repo](https://github.com/apollographql/federation/pull/135/commits/e4eab5428c8927a76b7f1d4f9857952c6c711715), Lerna no longer sees changes related to the `@apollo/query-planner-wasm` package and therefore won't suggest a publish to that package when appropriate.

**Comment by trevor-scheer** [comment]
Half-resolved by: https://github.com/apollographql/federation/pull/298

Hopefully, ^ is an interim solution to something better so I'll leave this issue open for now.

**Comment by pcmanus** [comment]
Closing as outdated (`query-planner-wasm` has been removed).
