### ISSUE TITLE
Directives on `QUERY`, `MUTATION`, or `SUBSCRIPTION` are not passed to subgraphs

### ISSUE THREAD

**Issue by lleadbet** [apollographql/federation#2961]
**Describe the bug**

When using a directive that uses one of `QUERY`, `MUTATION`, or `SUBSCRIPTION`, the router strips it before sending the request to the subgraph. 

**To Reproduce**

Given the below two subgraphs:

Subgraph 1:
```gql
directive @operation on MUTATION | QUERY | SUBSCRIPTION
directive @field on FIELD

type Foo @key(fields: "id") {
  id: ID!
}
type Query {
  foo: [Foo]
}
```

Subgraph 2:

```gql
directive @operation on MUTATION | QUERY | SUBSCRIPTION
directive @field on FIELD

type Foo @key(fields: "id") {
  id: ID!
  bar: String
}
```

It will generate the following query plan:

```gql
QueryPlan {
  Sequence {
    Fetch(service: "foo") {
      {
        foo @field {
          __typename
          id
        }
      }
    },
    Flatten(path: "foo.@") {
      Fetch(service: "bar") {
        {
          ... on Foo {
            __typename
            id
          }
        } =>
        {
          ... on Foo {
            bar @field
          }
        }
      },
    },
  },
}
```

With this query: 

```gql
query Operation @operation{
  foo @field {
    bar @field
  }
}
```

We can see that the `FIELD` directive works, however the one using the operation-level location is not. 

**Expected behavior**

The operation-level directives are persisted to the initial subgraph.

**Comment by abernix** [comment]
@lleadbet We moved this to the `federation` repository as this appears to be a query planner issue (query planner runs inside the router, but lives in this repo right now)

**Comment by duckki** [comment]
I merged the PR (https://github.com/apollographql/federation/pull/2967) that fixes this issue.
