### ISSUE TITLE
Using Custom Schema Registry

### ISSUE THREAD

**Issue by Danwakeem** [apollographql/federation#304]
## Description
It would be nice to have the option to use a custom schema registry rather than using the Apollo Studio registry when including a federated schema.

## Background
Where I am using Apollo the most, we currently have a gateway that is doing schema stitching and all of our schemas are registered to a custom schema registry we had created in house.

I has searched issues and things but didn't see any requests quite like this one. I am not sure if this is something the Apollo team would be interested in but maybe there are other out here that share our same need? 🤷‍♂️ 

## Ideas (?)
I had some ideas how this could happen so I will share them here and you guys can tell me what you think 😄 

1. Allow people to include their own logic to fetch/update the remote schemas.

This would leave the implementation details of how the schemas for the remote services are fetched up to the person implementing the gateway.

With this approach we could simply expose the `typeDef` attribute on the [`ServiceEndpointDefinition` type](https://github.com/apollographql/federation/blob/main/gateway-js/src/index.ts#L48). So once the schemas are fetched then the gateway could just be created using a service list that looks something like this 👇 

```typescript
{ name: String, typeDef: DocumentNode }
```

2. Create a fourth option in the gateway library to fetch remote schemas from a managed location that isn't Apollo Studio.

This could potentially work the same as the existing managed gateway set up with Apollo Studio right now where it would include code to poll the third party schema registry or something like that. There are quite a few details that work out there but maybe this is a clear enough picture?

## Conclusion
Really just looking to gauge if you guys are interested in doing something like this and if you think either of my ideas could possibly work? 😎

**Comment by Danwakeem** [comment]
Just reading through the code more. Is this something that can already be accomplished by using the experimental update service definitions? 🤔

https://github.com/apollographql/federation/blob/main/gateway-js/src/index.ts#L271

**Comment by trevor-scheer** [comment]
(I wrote up this draft yesterday, but it seems you've found the place I would've pointed you to! - Here's what I wrote up anyway. Good find!)

Hey @Danwakeem, thanks for the descriptive issue.

You should be able to accomplish this by rolling some of your own logic and using the `experimental_updateServiceDefinitions` config option of the gateway.

You might start by looking here:
https://github.com/apollographql/federation/blob/c82fe5884fae770a63070a26fefd0c393f66f5d7/gateway-js%2Fsrc%2Findex.ts#L267-L272

From there, you can see what the gateway does by default (`this.loadServiceDefinitions()`) and imitate that behavior with fetches to your own registry.

Let me know if you have any questions or if this doesn't satisfy your requirements.

**Comment by Danwakeem** [comment]
Awesome thank you @trevor-scheer I will reach out if we run into any issue with it 😎
