### ISSUE TITLE
Services traces not being sent to gateway

### ISSUE THREAD

**Issue by lucapasquale** [apollographql/federation#308]
When I request directly to the service, it provides the tracing information for each field inside the `extensions.tracing` response. But, if I make the same request to the gateway, which will send a sub query to the service, it only returns tracing information from the whole request, instead of from each field.

On the example repository i've used Nest, but using only the apollo-server directly it has the same problem.

### Quering the service directly:
![image](https://user-images.githubusercontent.com/15659967/102925931-f73f1880-4472-11eb-9d69-0735a379a6a2.png)

### Quering the gateway:
![image](https://user-images.githubusercontent.com/15659967/102925979-01611700-4473-11eb-8d03-e21adf32da96.png)

## How to reproduce:

 - Clone this test repository: https://github.com/lucapasquale/federation-test
 - Start the service: `cd service-1 && yarn && yarn start`
 - Start the gateway: `cd gateway && yarn && yarn start`
 - Execute this query directly to the service (`localhost:3000`)
```graphql
{
  product {
    id
    name
    price
  }
}
```
 - Execute the same query on the gateway (`localhost:3001`)

## Expected behavior:

Show the tracing information from a query, with the timings for ALL fields in the query

## Actual behavior:

Only returning tracing information from the top-level query, without the timings from each field of the returned types

## Versions:

Node: v12.20.0
Yarn: 1.22.5

#### Service
 - "@apollo/federation": "^0.20.7",
 - "@nestjs/graphql": "^7.9.1",
 - "apollo-server-express": "^2.19.0",
 - "graphql": "^15.4.0",
 - "graphql-tools": "^7.0.2",

#### Gateway
 - "@apollo/federation": "^0.20.7",
 - "@apollo/gateway": "^0.21.4",
 - "@nestjs/graphql": "^7.9.1",
 - "apollo-server-express": "^2.19.0",
 - "graphql": "^15.4.0",
 - "graphql-tools": "^7.0.2",

**Comment by Rapol** [comment]
We opened a ticket last year in apollo server because we thought the problem was in there. Today we revisited the ticket and found the same problem that you describe, tracing is returned by the service but not by the gateway.

Another repository that reproduce the problem: https://github.com/Rapol/azure-apollo-tracing-test

**Comment by Rapol** [comment]
Seems that tracing was overlooked for apollo gateway. The tracing plugin calculates timings for resolvers but the gateway doesnt call any resolvers. If you turn on tracing at the gateway it will just calculate the overall request/response timing. The plugin doesn't know that it is a gateway so it cant forward or recalculate these values.

Digging a bit deeper, apollo gateway doesnt seem to care about the extensions property that its returned by the underlying service. 

https://github.com/apollographql/federation/blob/6ceea3534cb6a9d340b0b77562941dd24b183bc1/gateway-js/src/executeQueryPlan.ts#L82-L91

This is where the gateway executes the call to the services and it just grabs the data of the graphql response. I tried deconstructing extensions but it is undefined.

Overall, this seems more than a simple bugfix and we might need some direction from the apollo team on how to support tracing for federation.

PS. Found this issue which is somewhat related but I believe this got fixed when tracing was ported to a plugin
https://github.com/apollographql/apollo-server/issues/4116

**Comment by Rapol** [comment]
Just found this https://www.apollographql.com/docs/federation/metrics/

Seems that tracing for apollo gateway is integrated with apollo studio. Not sure if there's a way to expose the metric information in the response instead of sending it to apollo studio

**Comment by lucapasquale** [comment]
> Just found this [apollographql.com/docs/federation/metrics](https://www.apollographql.com/docs/federation/metrics/)
> 
> Seems that tracing for apollo gateway is integrated with apollo studio. Not sure if there's a way to expose the metric information in the response instead of sending it to apollo studio

Yeah, that seems to be it! It doesn't show on the `extensions` but if I setup apollo studio it works there. Thanks for the help!

![image](https://user-images.githubusercontent.com/15659967/104103426-cdfaf680-5280-11eb-9c7b-85bb9c5109e4.png)
