### ISSUE TITLE
Undefined variable reference in generated subgraph query

### ISSUE THREAD

**Issue by carldunham** [apollographql/federation#3112]
## Describe the bug
[This repo](https://github.com/carldunham/apollo-router-5648) includes schema and a sample query that fails validation using the new Rust validation code.

## To Reproduce
1. Setup services: clone the repo, run `make run`
3. Submit request in `query.graphql`, provide a value for "time" (can be any enum value).

## Expected behavior
The query should succeed.

## Output
```
{
  "errors": [
    {
      "message": "Variable \"$time\" is not defined.",
      "locations": [
        {
          "line": 1,
          "column": 572
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    },
    {
      "message": "Variable \"$time\" is not defined.",
      "locations": [
        {
          "line": 1,
          "column": 572
        }
      ],
      "extensions": {
        "code": "GRAPHQL_VALIDATION_FAILED"
      }
    }
  ]
}
```
yet `$time` is clearly defined and used.

## Desktop (please complete the following information):
 - OS: iOS
 - Version 

## Additional context
Router version v1.52.0
Rover version 0.12.2

**Comment by goto-bus-stop** [comment]
OK perfect, thank you. It looks similar to an issue we had in the work-in-progress Rust query planner that has since been fixed.

Moved the issue to the federation repo so the JS query planner team can have a look at prioritising this.

**Comment by duckki** [comment]
I agree this looks similar to the Rust QP bug that @goto-bus-stop fixed recently.

**Comment by clenfest** [comment]
Hey @carldunham, can you confirm that this is not an issue if you have query fragment generation turned on? i.e. the following in your router yaml:

```yaml
supergraph:
  generate_query_fragments: true
```

Not sure if that's an option for you while waiting for the fix.

**Comment by carldunham** [comment]
Hi, Chris. I see the same behavior with that setting. Tried setting it to `true` and to `false`, still having the same result.
