### ISSUE TITLE
Issues when using @interfaceObject in combination with fragments

### ISSUE THREAD

**Issue by oskargotte** [apollographql/federation#3184]
### Issue Description

Consider these simplified schemas from the [interface extension example]( https://www.apollographql.com/docs/graphos/schema-design/federated-schemas/entities/interfaces#example-schemas) where Subgraph B extends the Media interface and hence the implementing Book type from Subgraph A with an extra `review` field.

<table>
<tr>
<td> Subgraph A  </td> <td> Subgraph B </td>
</tr>
<tr>
<td>
 
```graphql
interface Media @key(fields: "id") {
  id: ID!
  title: String!
}

type Book implements Media @key(fields: "id"){
  id: ID!
  title: String!
}
```
</td>
<td>

```graphql
type Media @key(fields: "id") @interfaceObject {
  id: ID!
  review: Int!
}

type Query {
  topRatedMedia: [Media!]!
}
```
</td>
</tr>
</table>

One can query for Media with `title` from Subgraph A and `review` from Subgraph B like this

```graphql
topRatedMedia {
  title
  review
}
```

One can use a fragment to get the `review` field only for Book types in case there are more implementations of the Media interface

```graphql
topRatedMedia {
  title
  ... on Book {
    review
  }
}
```

However, if `__typename` fields are added to the previous query (_which is what the Apollo Client would do_)
```graphql
topRatedMedia {
  __typename
  title
  ... on Book {
    __typename
    review
  }
}
```
the query fails silently with the data being `null`, no error in the response and no error in  the router logs but an extension in the response
```json
{"data":null,"extensions":{"valueCompletion":[{"message":"Cannot return null for non-nullable array element of type Media at index 0","path":["topRatedMedia",0]},{"message":"Cannot return null for non-nullable field [Media!]!.topRatedMedia","path":["topRatedMedia"]}]}}
```

### Link to Reproduction

https://codesandbox.io/p/devbox/nervous-silence-5rpvys

### Steps to reproduce

Open the sandbox link above and try the different queries

**Comment by oskargotte** [comment]
Closely related to #2743 which is solved for the queries mentioned in the issue but would still fail on e.g.
```graphql
  searchProducts {
    id
    ... on Book {
      __typename
      reviews
    }  
  }
```
Seems like an issue with the query plan.

**Comment by tninesling** [comment]
Hi, @oskargotte. Thanks for the report.

We recently fixed a similar issue in the Apollo Router, which is the spiritual successor to the Apollo Gateway in this repository. The patch for that issue was release in Router v1.58.0, and I have confirmed it returns the expected data for your example. Would switching to Apollo Router work for your use case?

**Comment by oskargotte** [comment]
Thanks for the response and the good news that the issue is fixed. I tested and i t worked with Router v1.58.0.
I actually did run into the issue when using the Router v1.57.1 but I should have mentioned it in the report.

Btw, when creating a Bug issue there is this [link](https://codesandbox.io/p/sandbox/apollo-gateway-ckyqqj) to a sandbox to start off from when reproducing the issue. Perhaps the sandbox should be using the Router instead?

Anyhow, great to see the issue fixed. Is there a PR to link?

**Comment by tninesling** [comment]
That's a great callout on the sandbox. I'll check with the team if we want to update that to use Router or if there's still sufficient utility in being able to create reproductions with Gateway.

The Router fix for this issue was https://github.com/apollographql/router/pull/6250.
