### ISSUE TITLE
Unknown type `_Entity` while pushing schema to Apollo

### ISSUE THREAD

**Issue by adikari** [apollographql/federation#321]
I am looking to deploy my implementing service schema to apollo federated graph. I am generating a local schema during then pushing that schema to apollo graph. However, when I push the schema I am getting an error as follows:

![image](https://user-images.githubusercontent.com/1757714/104269172-bd998480-54e9-11eb-843c-335deeaa594b.png)

The content of schema looks as follows:

```
extend type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
  report: Report
}

type Report @key(fields: "id") {
  id: ID!
}
```

Following is the code, I am using to generate the schema and write it to a file.

```
#!/usr/bin/env node

const { printSchema } = require('@apollo/federation');
const fs = require('fs');
const path = require('path');

const { makeSchema } = require('../src/graphql/schema');

const output = path.resolve(process.cwd(), 'schema.gql');

Promise.resolve()
  .then(makeSchema)
  .then(printSchema)
  .then(schema => fs.writeFileSync(output, schema, 'utf-8'))
  .catch(err => {
    console.error(err.message);
    process.exit(1);
  });
```
Following is the code for `src/graphql/schema`.

```
const { buildFederatedSchema } = require('@apollo/federation');
const reportSchema = require('./schema/report');

const makeSchema = () => buildFederatedSchema([reportSchema]);

module.exports = { makeSchema };
```

I am not entirely sure if I am doing something wrong or this is an actual issue. Looking at the documentation there are not many examples of pushing the local schema to Managed Gateway.

**Comment by abernix** [comment]
The `buildFederatedSchema` method is to be used at runtime to enable the federated functionality; the `_entities` and `_service` types should not be present in the schema that you are pushing to Apollo Studio.  In your case, it looks like you may just want to push `reportSchema`?

If you have multiple schemas to push, you should be able to concatenate them together into one object.
