### ISSUE TITLE
Apollo Federation/Gateway doesn't support Cache Control

### ISSUE THREAD

**Issue by RichiCoder1** [apollographql/federation#356]
It doesn't look like `@apollo/federation@0.9.0` and `@apollo/gateway@0.10.0` support `@cacheControl` directives or cache control hints.

Related: https://github.com/apollographql/apollo-server/issues/3181

### Expected
 
Using static or dynamic cacheControl hints will result in cache-control http headers.

### Actual

No headers are sent, and the hints are empty when `cacheControl: true` in `ApolloServer`.

### Code Example:

```js
import { gql } from 'apollo-server'

const typeDefs = gql`
    type Test @key(fields: "id") @cacheControl(maxAge: 60, scope: PRIVATE) {
        id: ID!
     }
`;

export { typeDefs }
```

Error: `UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Unknown directive "cacheControl".`

**Comment by eliw00d** [comment]
> In reference to @ctpaulson's comment above, we also had to do some additional work in the gateway to ensure that the resulting headers were combined appropriately:
> 
> First, we create a new datasource that collects the headers:
> 
> ```
> 'use strict';
> 
> const { RemoteGraphQLDataSource } = require('@apollo/gateway');
> 
> /**
>  * CachedDataSource
>  *
>  * Intended to be used in an `ApolloGateway`, in conjunction with
>  * the `CacheControlHeaderPlugin`. Takes all responses and their
>  * `Cache-Control` headers and adds them to a `cacheControl` array
>  * on the context.
>  *
>  * When used in conjunction with the `CacheControlHeaderPlugin`,
>  * the `cacheControl` array of headers will be used to calculate the overall
>  * `Cache-Control` header that should be set on the final response.
>  */
> class CachedDataSource extends RemoteGraphQLDataSource {
>   async didReceiveResponse (response, _request, _context) {
>     const cacheControl = response.headers.get('Cache-Control');
> 
>     if (!_context.cacheControl || !Array.isArray(_context.cacheControl)) {
>       _context.cacheControl = [];
>     }
> 
>     _context.cacheControl.push(cacheControl);
> 
>     return super.didReceiveResponse(response, _request, _context);
>   }
> }
> 
> module.exports = {
>   CachedDataSource
> }
> ```
> 
> And we also have a special plugin to calculate the overall cache-control value and set the headers:
> 
> ```
> 'use strict';
> 
> /**
>  * The regext for finding the max-age value
>  */
> const CacheHeaderRegex = /^max-age=([0-9]+), public$/;
> 
> /**
>  * Calculates the minimum max-age between the headers, retruns a new header
>  *
>  * @param {string[]} cacheControl - array of cache-control headers
>  */
> const calculateCacheHeader = (cacheControl = []) => {
>   const maxAge = cacheControl.map((h) => CacheHeaderRegex.exec(h))
>     .map((matches) => matches || [])
>     .map((matches) => matches[1] || 0) // eslint-disable-line no-magic-numbers
>     .reduce((acc, val) => Math.min(acc, val), +Infinity);
> 
>   return maxAge ? `max-age=${maxAge}, public` : 'no-cache';
> };
> 
> /**
>  * CacheControlHeaderPlugin
>  *
>  * Intended for use in conjunction with `CachedDataSource`.
>  *
>  * When used in an `ApolloGateway` with the `CachedDataSource`,
>  * takes the generated array of `cacheControl` headers on the context
>  * and calculates the minimum max-age of all the headers and then
>  * sets that max-age on the response.
>  *
>  * This is intended to be used with federated schemas that return
>  * `Cache-Control` headers, as supported by Apollo CacheControl.
>  */
> const CacheControlHeaderPlugin = {
>   requestDidStart () {
>     return {
>       willSendResponse ({ response, context }) {
>         const cacheHeader = calculateCacheHeader(context.cacheControl);
>         response.http.headers.set('Cache-Control', cacheHeader);
>       }
>     };
>   }
> };
> 
> module.exports = {
>   CacheControlHeaderPlugin
> }
> ```
> 
> And then we wire it all up in the configuration:
> 
> ```
> const gateway = new ApolloGateway({
>   ...
>   buildService({ url }) {
>     return new CachedDataSource({ url });
>   }
> });
> 
> const server = new ApolloServer({
>   gateway,
>   ...
>   subscriptions: false,
>   plugins: [
>     CacheControlHeaderPlugin
>   ],
>   persistedQueries: {
>     ...
>   },
>   ...
> });
> ```

It's actually a lot less complicated than this, since the servers behind the gateway actually do respond with the `age` and `cache-control` headers already. In addition to adding the directive to buildFederatedSchema and using the responseCachePlugin, I just did this in the gateway:

```javascript
new ApolloGateway({
  buildService: ({ url }) =>
    new RemoteGraphQLDataSource({
      didReceiveResponse({ context: { req, res } = {}, response }) {
        const age = response.http?.headers?.get('Age')
        if (age) {
          res?.append('Age', age)
        }
          
        const cacheControl = response.http?.headers?.get('Cache-Control')
        if (cacheControl) {
          res?.append('Cache-Control', cacheControl)
        }
        return response
      }
    })
})
```

I can't seem to get it to work using `response.http?.headers?.append` so I had to use the underlying express response.

Everything works after that except for invalidating the cache for mutations, which ended up killing this for us, but just in case it is helpful for anyone else.

**Comment by glasser** [comment]
We're hoping to improve this to work by default. See plan at https://github.com/apollographql/apollo-server/issues/5449
