### ISSUE TITLE
Hide fields from public federated gateway

### ISSUE THREAD

**Issue by fernandobandeira** [apollographql/federation#371]
Currently with schema stitching we can use the transformSchema to hide some root fields from the public graphql endpoint, we have some queries and mutations that are being used by cronjobs and scheduling services currently that shouldn't appear in the public graphql endpoint, they're supposed to be used only internally.

Currently we're using a function like this in the gateway:
```javascript
const removeHiddenFields = (schema, hiddenFields) => transformSchema(schema, [
  new FilterRootFields(
    (operation, rootField) => hiddenFields.indexOf(rootField) === -1
  )
])

// usage example
removeHiddenFields(schemas.notifications, ['scheduledNotifications'])
```

Could we have a directive for this, maybe? `@private` for example, this way we can filter which fields will be available to the public.

**Comment by tgrowden** [comment]
> @fernandobandeira our intention is to add an `@internal` directive at the service level that will do this! Should be worked on really soon!

@jbaxleyiii is there a place where the progress is being tracked on this? It would be really handy to have and I was wondering what the status is.

**Comment by setchy** [comment]
We're using apollo-gateway /w Apollo Studio federating a number of SpringBoot GraphQL implementing services.  

Each of the SpringBoot implementing services have a [GraphQLFieldVisibility](https://www.graphql-java.com/documentation/v16/fieldvisibility/) utility that ensures any fields/types that the client doesn't have permissions to are not present in the introspection SDL.

This is working great at an independent implementing graph-service level.

However our federated gateway doesn't respect this as its super-schema is primed from Apollo Studio.  Fields are still visible within the introspection SDL and therefore tooling like Playground / Voyager, however any query to these will fail as they don't exist in the downstream SDL for that particular client.

Would really value some input / guidance on how to solve for this at the Gateway level.

**Comment by andrewmcgivery** [comment]
@trevor-scheer @abernix Are there any plans to add the `@internal` directive mentioned in this issue? Seems like there has been a lot of interest in this.

**Comment by setchy** [comment]
Seems like to upcoming schema contracts and `@tags` directive as presented in the May product webinar will go a long way to solving this

**Comment by prasek** [comment]
@setchy yes we're working on adding `@inaccessible` and `@tag` support in subgraph schemas and they will compose into the supergraph using a union rollup.

`Schema Contracts` in Apollo Studio will rely on `@tag` and `@inaccessible` to simplify maintaining multiple contract variants using policy rules you can define.

**Comment by dborstelmann** [comment]
Love the contracts feature but we aren't on the enterprise plan.  Just a plug here as a paying Team customer that we would love this feature to be opened up so we can use the same infra for internal and external APIs.

**Comment by cpeacock** [comment]
Hey there!  We are looking for feedback on this issue around `@inaccessible`: https://github.com/apollographql/federation/issues/1178 which I believe solves the problem laid out in here (and this issue is super old!).  Please feel free to discuss there as we're planning on tackling parts of that after our GA of Federation 2, and also feel free to reopen this if it doesn't cover what you're expecting.

**Comment by rhyek** [comment]
`@inaccessible` seems good for hiding fields from a public federation gateway, but what about not hiding them in an internal one. I want my services to be able to take advantage of federation and automatic field resolution through sub graphs exactly like an internet client can, but also be able to access those hidden fields.

**Comment by ayushs-2k4** [comment]
@rhyek Did you find a solution?
