### ISSUE TITLE
There is no way to enable federated traces when `ENGINE_API_KEY` env variable is set

### ISSUE THREAD

**Issue by sponomarev** [apollographql/federation#385]
According to the [Federated Traces documentation](https://www.apollographql.com/docs/apollo-server/federation/metrics/#turning-it-on), to enable them we should either 

> ensure that implementing services do not report metrics as well, do not provide them with an ENGINE_API_KEY

or

> set { engine: true, reporting: false } in the constructor options to ApolloServer.

Unfortunately, the current implementation of the `apollo-server` package doesn't respect `reporting: false` option and `ENGINE_API_KEY` has precedence over it. 

Check if `engineReportingAgent` is already set to enable federated traces

https://github.com/apollographql/apollo-server/blob/a94f403f5e35f4d9e6193765771b437586f3e3a6/packages/apollo-server-core/src/ApolloServer.ts#L517-L529

`engineReportingAgent` is initialized  if `engineServiceId` is set

https://github.com/apollographql/apollo-server/blob/a94f403f5e35f4d9e6193765771b437586f3e3a6/packages/apollo-server-core/src/ApolloServer.ts#L319-L325

`engineServiceId` is set from `engineApiKey` from ENV

https://github.com/apollographql/apollo-server/blob/a94f403f5e35f4d9e6193765771b437586f3e3a6/packages/apollo-server-core/src/ApolloServer.ts#L85-L95

**Comment by glasser** [comment]
This behavior changed in Apollo Server 2.18.

First, [we entirely removed the special case for inline (federated) traces when the API key is set](https://www.apollographql.com/docs/apollo-server/migration-engine-plugins/#options-for-apolloserverplugininlinetrace) which fixes your issue directly.

Secondly, we made it possible to explicitly enable or disable inline tracing by installing the ApolloServerPluginInlineTrace and ApolloServerPluginInlineTraceDisabled plugins.
