### ISSUE TITLE
@provides directive doesn't work with interfaces (@apollo/federation)

### ISSUE THREAD

**Issue by vitramir** [apollographql/federation#386]
It throws with error "<FIELD> -> uses the @provides directive but `<FIELD>` returns `<INTERFACE_TYPE>`, which is not an Object or List type."

Does anybody work on this issue already? Or should I fix it myself?

Important notice:
It works as expected if I just comment throw line.

**Comment by cpeacock** [comment]
Hi there!  We believe this is fixed in our Federation 2 alpha release, but feel free to reopen against that set of branches if the larger issue isn't fixed.
