### ISSUE TITLE
Federated metrics doesn't report parse or validation errors from the backend

### ISSUE THREAD

**Issue by glasser** [apollographql/federation#390]
The extensionStack.format() call is not invoked when there are parse or validation errors, so no federated trace is provided to gateway.

The errors are still returned to gateway outside of the trace, but are treated as downstream errors so they are only sent to the end user, not in the reported trace.

We could fix this by calling format() more often, or by not skipping downstream parse/validation errors (if we can detect them).

**Comment by pcmanus** [comment]
This issue seemed pretty implementation specific and has been 2+ years without updates, so I'm wondering if it's still an issue (and if so, how much it matters)? I'll admit I could use some more specifics on what was the problem to be able to judge if that is still a thing. Anyway, in the interest of our spring cleaning of old tickets, I'm going to tentatively close this, but you feel there is still something important to be done here, feel free to re-open/complain (but would appreciate a few more details if so).

**Comment by glasser** [comment]
The actual "extension stack" mechanism has been completely replaced by a different mechanism.

I don't know if the issue in question has been really fixed; it might be worth a test if it matters. IIUC this is an issue if for some reason the gateway/router is generating non-valid operations.
