### ISSUE TITLE
Gateway is stripping operation names when forwarding to federated service

### ISSUE THREAD

**Issue by rtymchyk** [apollographql/federation#395]
I'm not quite sure if this is a bug or a question, but I can observe that if apollo-client fires a query like this:
```
{
  "operationName": "AuthenticatedRouteViewerQuery",
  "variables": {},
  "query": "query AuthenticatedRouteViewerQuery { viewer { user { __typename id } } }"
}
```

And it passes through the gateway, the back-end ruby/rails service reports:
```
Processing by GraphqlController#execute as */*
Parameters: {"query"=>"{viewer{user{id __typename}__typename}}", "variables"=>{}, "graphql"=>{"query"=>"{viewer{user{id __typename}__typename}}", "variables"=>{}}}
```

I am running:
`@apollo/gateway@0.14.1`
`apollo-server@^2.12.0`

Clearly operation names are intact because I can see them in the Apollo Graph Manager metrics section, but downstream they are not visible in the actual service.

**Comment by rtymchyk** [comment]
I think there was a small gap in the solution posted above, so here's what I've ended up with:

```javascript
const apolloServer = new ApolloServer({
  context: ({ req }) => {
    return { operationName: req.body.operationName }
  }
})

...

export default class RemoteDataSource extends RemoteGraphQLDataSource {
  willSendRequest({ request, context }) {
    const operationName = context.operationName
    if (operationName) request.http.headers.set('X-Operation-Name, value)
  }
}
```

**Comment by abernix** [comment]
Good news! This should be improved by #1550 and that improvement will go out in a new release of the `2.x` packages next week!
