### ISSUE TITLE
Conditional `@skip` + `@include` directives don't prevent unnecessary fetches

### ISSUE THREAD

**Issue by smyrick** [apollographql/federation#457]
## Description
When using the `@include` or `@skip` directives on fields, the gateway will still construct a query to the underlying service which will execute the resolvers.

Even if the directive is applied on the field itself and not the selection set, the query plan still includes the service

![Screen Shot 2021-02-08 at 10 58 29 AM](https://user-images.githubusercontent.com/2446877/107271510-331d4580-6a01-11eb-857f-ed223e226dcb.png)

### Reproducible Sandbox

https://codesandbox.io/s/v368r9ml47?file=/index.js

 #### Query 
```graphql
query TestQuery {
  me {
    name
    ...ReviewsFragment @include(if:false)
  }
}

fragment ReviewsFragment on User {
  reviews {
    id
    body
  }
}
```

**Comment by glasser** [comment]
In the short term we should consider rejecting operations with `@skip`/`@include`, or at least if it's used on the top level of a mutation or something.

**Comment by meip** [comment]
Do you have an update on this? Is this related to https://github.com/apollographql/federation/issues/179?

**Comment by abernix** [comment]
There is a more principled way we should fix this in the query planner by adapting its format, however, the difficulty of doing so is a bit higher.  Paraphrasing a suggestions another approach (from a conversation outside GitHub) which might fix most cases (at least, believed to be _good enough_ for the short-term, _without_ changing the query plan): If the Gateway subgraph fetch has a top-level `@skip` or `@include`, evaluate the condition and skip the whole fetch if possible.  This involves some additional runtime analysis that wouldn't be needed if we make this part of the query plan, but it could get the job done.

So, within [`executeFetch`](https://github.com/apollographql/federation/blob/9494b0bf13395d7131614258a3d3e7f4996cf007/gateway-js/src/executeQueryPlan.ts#L333):

https://github.com/apollographql/federation/blob/9494b0bf13395d7131614258a3d3e7f4996cf007/gateway-js/src/executeQueryPlan.ts#L333

1. parse `fetch.operation` (or preferably get the pre-printed `DocumentNode`?)
2. Identify `@skip`/`@include` at the top-level
3. If present and the condition is false, merely return from `executeFetch`.

There are probably other approaches.

**Comment by glasser** [comment]
@trevor-scheer was this fixed by #1113?

**Comment by trevor-scheer** [comment]
@glasser yeah, not sure why I left this issue hanging. Did this surface in an interesting way or did you just come across this by chance?

**Comment by glasser** [comment]
There was a community question about skip/include and I couldn't remember whether we still had a caveat around "skip/include don't work the way you'd expect with federation" or not.
