### ISSUE TITLE
Understand why Gateways fail frequently at loading schemas

### ISSUE THREAD

**Issue by glasser** [apollographql/federation#463]
#355 is about ensuring that failures to load the schema can be detected, logged, and acted upon by users, but we still should understand why this happens in practice. We have one bug report of a `getaddr EAI_AGAIN` which seems like a promising thread to track down. We should understand if this is something that will be resolved by moving to cloudconfig, or if it can be avoided with code changes, or if it requires customers to do something else in their environment (eg change how they do DNS).

**Comment by andytruong** [comment]
This is happening to us!

**Comment by trevor-scheer** [comment]
@andytruong can you please elaborate what you're seeing in a separate issue? Recent gateway versions are using a completely different system (named Uplink) and if you're seeing it there that would be helpful information. Given the age of this issue and the fact that we're moving away from the previous system, I'm going to close this issue. (@glasser should feel free to reopen if he thinks this is still ongoing and worth resolving)
