### ISSUE TITLE
Missing `name` property in the `ApolloGateway` `serviceList` configuration resolves with "unreachable" error and wasm stacktrace.

### ISSUE THREAD

**Issue by spencerarogers** [apollographql/federation#473]
## Summary

Opening per the request in [#439](https://github.com/apollographql/federation/issues/439#issuecomment-783367151).

When initializing `ApolloGateway` and the `serviceList` array contains an object missing a `name` property, the gateway will start up and load the implementing service's schema properly but any queries that hit this service will result in an error.

Invalid config:
```js
const gateway = new ApolloGateway({
  // NOTE: Here the we have a service with a valid `url` but a missing `name` property.
  serviceList: [{"not-name":"my-service", "url":"http://localhost:4001/graphql"}]
});
```

The stacktrace returned by the gateway server looks like this:

```json
{
  "errors": [
    {
      "message": "unreachable",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "RuntimeError: unreachable",
            "    at <anonymous>:wasm-function[525]:0xa165d",
            "    at <anonymous>:wasm-function[583]:0xa403a",
            "    at <anonymous>:wasm-function[718]:0xa6e56",
            "    at <anonymous>:wasm-function[688]:0xa6828",
            "    at <anonymous>:wasm-function[720]:0xa6eba",
            "    at <anonymous>:wasm-function[654]:0xa5df7",
            "    at <anonymous>:wasm-function[347]:0x934a7",
            "    at <anonymous>:wasm-function[49]:0x5288f",
            "    at <anonymous>:wasm-function[31]:0x45fa7",
            "    at <anonymous>:wasm-function[561]:0xa326f"
          ]
        }
      }
    }
  ]
}
```
## Reproduction

Here is a simple working reproduction of the issue described above with instructions in the README.md:

https://github.com/spencerarogers/apollo-federation-439-repro

Then in this `multiple-implementing-services` branch there is another reproduction in which there is 1 incorrectly configured service and 1 correctly configured service. This illustrates that the gateway can continue to function for properly configured services but error whenever a query is sent to the incorrectly configured implementing service:

https://github.com/spencerarogers/apollo-federation-439-repro/tree/multiple-implementing-services

**Comment by abernix** [comment]
@spencerarogers Is this still happening for you on the latest version?

**Comment by spencerarogers** [comment]
@abernix No, I tested out @apollo/gateway v0.34.0 and now the gateway reports that it has an invalid configuration on load and GraphQL queries fail as expected.

`node gateway-server.js`
```
This data graph is missing a valid configuration. Cannot read property 'replace' of undefined
```

Query response:
```
{
  "errors": [
    {
      "message": "This data graph is missing a valid configuration. More details may be available in the server logs.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: This data graph is missing a valid configuration. More details may be available in the server logs.",
            "    at /home/spencer/code/apollo-federation-439-repro/node_modules/apollo-server-core/dist/ApolloServer.js:216:23",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    }
  ]
}
```

**Comment by abernix** [comment]
Thanks for confirming and thanks for reporting originally! I'll close this since this looks a lot better and seems to be behaving better.

That said, I would certainly believe we'd happily take a PR that threw a nicer message than the _undefined property_ message in the actual implementation if you were so inclined! 😀
