### ISSUE TITLE
query-planner: consider using an alternative to `vec` for modeling data in `context.rs`

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#476]
This is to track additional work noted in this review: https://github.com/apollographql/federation/pull/264#pullrequestreview-520763180

~Quoting:

> there are a lot of `expect`s here that suggest that a `vec` has only one item- why are we using a `vec to model this data?
>
> [...] would still encourage us to use proper error handling. even if we reason it is impossible, code changes, and those assumptions change. using errors and `?` is much better than panicking, even if the panic has a messge.

See https://github.com/apollographql/federation/issues/477 for some related/granular tasks.

**Comment by pcmanus** [comment]
Closing as this is outdated.
