### ISSUE TITLE
query-planner: decompose nested complexity in `context.rs`.

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#477]
Based on the unaddressed feedback left in https://github.com/apollographql/federation/pull/264#pullrequestreview-520763180 (to prevent blocking the merge of that PR) and referring to [this section of code](https://github.com/apollographql/federation/blob/6895b61c30bd2260c117f95c061f489d6ea0bb61/query-planner/src/context.rs#L221-L249):
https://github.com/apollographql/federation/blob/6895b61c30bd2260c117f95c061f489d6ea0bb61/query-planner/src/context.rs#L221-L249

In particular, note the comments:

* https://github.com/apollographql/federation/pull/264#discussion_r515170627
  > the logic here is hard to read and would benefit from being broken into some smaller functions
* https://github.com/apollographql/federation/pull/264#discussion_r515171505
  > this smells like it would be better as a struct w/impl
* https://github.com/apollographql/federation/pull/264#discussion_r515171695
  > is this potentially better as a default value?

Also relates to #476, which could resolve this.

**Comment by pcmanus** [comment]
Closing as this is outdated.
