### ISSUE TITLE
ci: convert to using CircleCI

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#540]
This is to track an intent/suggestion on my part to change our test-suite in this repository from running within a mix of using GitHub Actions _and_ CircleCI to **just** using CircleCI.

This follows-up an outstanding TODO from https://github.com/apollographql/federation/pull/480 which revealed a number of design choices which prevent reusability of code that is necessary to repeat in a workflow/fanout design.  CircleCI has supported this (and basic YAML features, like Anchors/Aliases) for a while now plus we already run all of our other tests (not only here, but also in other repositories) in CircleCI.  GitHub Actions are certainly nifty but a single, more powerful unified tool seems like a better choice for this particular task.

**Comment by benweatherman** [comment]
I think this is all done now. Please reopen or add new issues if needed!
