### ISSUE TITLE
No dist folder in the @apollo/query-planner-wasm

### ISSUE THREAD

**Issue by FrankMerema** [apollographql/federation#558]
The current version 0.2.2 doesn't include the dist folder, so the graphql is complaining about:

`Error: Cannot find module '/opt/app/node_modules/@apollo/query-planner-wasm/dist/index.js'`

I have downloaded the 0.2.1 and that one has the dist folder

It seems like a really easy fix :)

Thanks in advance!

**Comment by FrankMerema** [comment]
And because of this the @apollo/query-planner which depends on the 0.2.2 breaks as well 😅

**Comment by FrankMerema** [comment]
And of course the @apollo/gateway": "^0.24.3" as well 😅

**Comment by glasser** [comment]
@FrankMerema There was some trouble publishing yesterday due to some changes to how we package that sub-package but I think it should be good as of `@apollo/gateway@0.24.4`. If you're still seeing problems with that version let us know!

**Comment by dionescu-shipserv** [comment]
There is an issue with `@apollo/gateway@0.24.4` - `Module not found: Error: Can't resolve './index_bg.js' of node_modules/@apollo/query-planner-wasm/module`
