### ISSUE TITLE
feat(gateway): optionally compute `instrospectionHeaders` per request via a function

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#604]
Ref
* https://github.com/apollographql/federation/pull/539#issuecomment-797667680
* https://github.com/apollographql/federation/pull/539#issuecomment-799347616

Relates to #563, though the change I'm recommending in this issue is a bit more short-sighted (still useful!)

It's reasonable to need to calculate `introspectionHeaders` dynamically / per request. Rather than reaching into the gateway's `config` object to modify them, we can provide an API for this. See linked comments for additional context.

**Comment by williamboman** [comment]
I'll take a look at this!

**Comment by williamboman** [comment]
https://github.com/apollographql/federation/pull/607
