### ISSUE TITLE
AWS Serverless, GateWay & JWT Tokens

### ISSUE THREAD

**Issue by johnlongo** [apollographql/federation#606]
Trying to pass a client jwt token to downstream Apollo server and I'm using introspectionHeaders to pass that token. When I review the request, I'm seeing two requests coming into the downstream server. One that has the jwt token and one that doesn't.  The body of the request that has the token looks like this ""body": "{\"query\":\"query __ApolloGetServiceDefinition__ { _service { sdl } }\"}"". The body of the request that **DOES NOT** have the token contains the GraphQL. Please advise what I can do to resolve the problem.

**Comment by trevor-scheer** [comment]
Hey @johnlongo - the `introspectionHeaders` is used specifically for when the gateway performs the query for a service's SDL for the purpose of composition _only_.

If you'd like to customize the outgoing federated requests, you'll need to do so with a custom `RemoteGraphQLDataSource`. There's a good writeup [in the docs](https://www.apollographql.com/docs/federation/gateway/#customizing-requests) about how to accomplish exactly what you're trying to do.

I'm going to close this. If you have feedback about the docs (i.e. did you look and have trouble finding?) that would be great to hear. Thanks!
