### ISSUE TITLE
Publish changelog notes under GH Releases

### ISSUE THREAD

**Issue by setchy** [apollographql/federation#636]
Would it be possible to begin publishing release notes for the federation packages?

This would make it easier for consumers to understand what are the non-breaking updates, and more importantly any potential breaking changes

**Comment by trevor-scheer** [comment]
Hey @setchy, there are `CHANGELOG.md`s within the federation and gateway subfolders where you can view these changes. Is the ask that these changes be published more formally via GH releases? I think this could be nice to implement.

**Comment by setchy** [comment]
Thanks @trevor-scheer - I'll pin that file.  

That's correct - publishing them in the GH Releases.  We use `renovate-bot` to automate dependency updates and it pulls release notes from GH and attaches them to our PRs.

**Comment by glasser** [comment]
Renovate does support CHANGELOG files, so we might just have some misconfiguration there. See https://github.com/renovatebot/renovate/issues/4724

**Comment by glasser** [comment]
(and looks like the logic is in this file: https://github.com/renovatebot/renovate/blob/master/lib/workers/pr/changelog/release-notes.ts)

**Comment by glasser** [comment]
(We definitely have it set up properly for `apollo-server`, as you can see in the release notes section of https://github.com/apollographql/federation/pull/623)

**Comment by setchy** [comment]
Thanks @glasser.  I can confirm that renovate is correctly pulling the PR change notes for `apollo-server`

**Comment by setchy** [comment]
I believe renovate is looking for the `CHANGLOG.md` at the root of https://github.com/apollographql/federation, which is why https://github.com/apollographql/apollo-server works

**Comment by setchy** [comment]
Example of the most recent Renovate PR showing the difference between @apollo/gateway and apollo-server-express
<img width="587" alt="Screen Shot 2021-06-12 at 08 52 31 " src="https://user-images.githubusercontent.com/386277/121781850-b21fb780-cb74-11eb-89c4-bd32b97d8765.png">

**Comment by setchy** [comment]
I believe this limitation in Renovate is causing the inconsistencies with this repo
https://github.com/renovatebot/renovate/issues/10954

**Comment by setchy** [comment]
Monorepo handling now available with Renovate v29.30.0 - https://github.com/renovatebot/renovate/pull/12543 

However these two issues will prevent use of this enhancement  
* #1263
* #1262

That said, going to close this issue

**Comment by setchy** [comment]
#1815
