### ISSUE TITLE
chore: Renaming of `FieldSet` x2

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#684]
A previous comment on a PR (which I for some reason had difficulty finding, but is captured in the description here: https://github.com/apollographql/federation/pull/656) recommends renaming our `FieldSet` type since we now have 2 of them and they are different. I would have just gone forward with the suggestion but I'm really not sure what to name them and thought maybe @martijnwalraven might have opinions.

https://github.com/apollographql/federation/blob/5b30ba8bb31e88a6f537f6f1fe0d23eb78722ec6/query-planner-js/src/composedSchema/metadata.ts#L35
https://github.com/apollographql/federation/blob/32f785202e86dc10b942391fb461e59ca80fed89/query-planner-js/src/FieldSet.ts#L67

**Comment by pcmanus** [comment]
Gonna close this one for a bit of issue-cleaning as I believe federation removed both of those types and I'm not sure we want  to bother with the `version-0.x` branch. If anyone feel like I'm wrong about that last part and it is still worth changing, please pardon my overstepping and feel free to re-open.
