### ISSUE TITLE
Update the Readme 

### ISSUE THREAD

**Issue by jbaxleyiii** [apollographql/federation#69]
The Readme currently describes the project to just be about the CLI. Since this now houses multiple OSS projects, we should update the readme and other repo assets to reflect that this is a general OSS monorepo for our rust code that services many different projects.

**Comment by ashleygwilliams** [comment]
thought: maybe we can have an overview readme, and then do individual readmes for each tool in their own directory? if we ever split the monolith, the docs will be ready, and i think in the meantime both maintainers and readers would navigate it more easily. would love to hear other folks' thoughts!

**Comment by jbaxleyiii** [comment]
@ashleygwilliams yeah I think that is definitely the way to go. It also helps from a packaing perspective for projects that get distributed where you want a project readme to stay in tact. Having a local one helps contributors and consumers alike.

**Comment by cpeacock** [comment]
@abernix doing some cleanup, seems like a close candidate?

**Comment by abernix** [comment]
Yes, this can be closed. We finally managed to get a fresh coat of paint on this with Federation 2 alpha and I think it frames things well (including the multiple release branches).  While this does continue to be a monorepo, the packages are of a single concern and the various pieces fit together coherently.

Furthermore, as suggested above, there are (now) individual `README` files in each directory with the exception of the `internal-js` package (published as [`@apollo/federation-internals`](https://www.npmjs.com/package/@apollo/federation-internals) and the (unpublished) `router-bridge`.  At least the latter will get a `README` soon as part of its publishing, and the internals package is just utility.  (I certainly wouldn't object to it getting a `README` that states that, but it's not particularly critical and it's not meant to be depended on directly.)

Thanks for opening the original issue and for the follow-up suggestions  🌊 👋 🤗
