### ISSUE TITLE
Incorrect @key federation directives do not get handled properly

### ISSUE THREAD

**Issue by ahctangU** [apollographql/federation#850]
Situation:

If I am uploading a schema with incorrect directive syntax, for example: (Notice the missing quotation marks)
```
  type MediaChapter @key(fields: id) {
    id: ID!
    nameJa: String!
    thumbnailUrl: String!
    contentTags: [ContentTag!]!
    length: String!
    timeCodeType: String!
    """
    In HH:MM:SS:FF format
    """
    startTimeCode: String!
    """
    In HH:MM:SS:FF format
    """
    endTimeCode: String!
    timeCodeMode: String!

    performances: [MediaPerformance!]!
    credits: [CapyCredit!]!
    parent: Media!
  }
```

`rover subgraph introspect` will not error. `rover subgraph check` will not error. Everything will pass! In fact, the directive will even render in Apollo Studio! However, when you actually try to compose the schema, the next subgraph check and publish will report the following error:
```
MediaChapter -> appears to be an entity but no @key directives are specified on the originating type.
```

I don't know what approach the Apollo team wants to take for this, but it was absolutely maddening to debug since every tool in the stack was reporting OK when it was in fact NOT OK.

**Comment by abernix** [comment]
Thanks very much for filing an issue here!  This must have been frustrating, indeed.  While this is syntactically valid GraphQL (the unquoted `id` is merely parsed as an `enum` property!) there is almost certainly something we can do to improve this via validation.  Thanks again!
