### ISSUE TITLE
[apollo-gateway] Question about nullability and cross-service joins

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation#860]
Hi @trevor-scheer, @jhampton and friends,

Any time the query planner calls another service, there's an additional chance of failure. Consider the following two-service federated graph:

```graphql
type User @key(fields: "id") {
  id: ID!
  name: String!
}
```
```graphql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: ReviewConnection!
}

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}
```

Because `User.reviews` is a non-nullable ReviewConnection, if the request to the Reviews service fails (due to a network partition or service downtime) the response will fail validation and we won't get any data at all.

```graphql
query UserReviews($id: ID!) {
  user(id: $id) {
    id
    name
    reviews { # returning null here means we won't get `user.id` or `user.name`
      nodes {
        id
        content
      }
   }
}
```

What are your thoughts on making `User.reviews` nullable to better support partial data? It's kind of a shame to leak implementation details into the schema. Are y'all documenting best practices like this anywhere?

Would we possibly want a schema linter that enforces that cross-service data is nullable to allow partial data?

Alternatively, would it be possible to handle failures like this?

```json
{
  "data": {
    "user": {
      "id": "1",
      "name": "Lenny",
      "reviews": {
        "nodes": [],
      }
    }
  },
  "errors": [
    {
      "message": "Error fetching User.reviews: Service is down",
      "path": ["user", "reviews"]
    }
  ]
}
```

I have no idea how you'd do this generically, but maintaining the contract by returning empty data plus an error would be very cool.

**Comment by prasek** [comment]
Thanks @kindermax will take a look 👍 cc @martijnwalraven @pcmanus @abernix - something to consider for the next round of Federation changes

**Comment by mjfaga** [comment]
Throwing my two cents in here. I would agree that forcing `null` in extending services is non-ideal for the reasons @kindermax sited above. 

Without breaking existing GQL spec expectations with regards to nullable vs. non-nullable fields, I wonder if something like a `@faultTolerant` directive (happy to debate a legit name for this at some point) on extended fields of a required type in federation can instruct the gateway to either:
1. (preferred) Keep fields as required, but return a custom ServiceOutageError value type hydrated with the correct information, During the federation process, this value type would be exposed by compiling it into the final schema as a union type.
2. Expose fields as nullable, but treat them as non-nullable internally, and if the underlying service experiences some sort of network error/500, handle that and populate the `errors` array in the response appropriately.

There is also a potential option to make this sort of functionality default in federated implementations, avoiding the use of a directive attribution unless you want to opt out of this sort of functionality... something like a `@propogateNetworkFailures` directive or the like.

## Option 1 Example

```gql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: ReviewConnection! @faultTolerant
}

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}
```
would compile to the following in the supergraph schema and guarantee a result set that clients explicitly detect and have to handle
```gql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: UserReviewsFaultTolerantPayload!
}

union UserReviewsFaultTolerantPayload = ReviewConnection | ServiceOutageError

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}

# I'm sure we can come up with something better here :)
type ServiceOutageError {
  serviceName: String!
  statusCode: Int!
  message: String!
}
```

## Option 2 Example

```gql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: ReviewConnection! @faultTolerant
}

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}
```
would simply compile to the following in the supergraph schema, where again, the `errors` object would be hydrated with the appropriate content that clients could use to decision off of
```gql
extend type User @key(fields: "id") {
  id: ID! @external
  reviews: ReviewConnection
}

type ReviewConnection {
  edges: [ReviewEdge!]!
  nodes: [Review!]!
  pageInfo: PageInfo!
}
```

**Comment by mjfaga** [comment]
The more I think about what I wrote above, the less I like it. Option 1 above actually feels like it starts to leak the internals of federation into our frontend by explicitly defining where services extend other services. I can't decided if this is a necessarily evil or not. 

Ensuring the gateway is returning sensible errors feels like a reasonable way to handle this, but either way, knowing that there was a service outage and handling that in our frontend doesn't feel much different.

**Comment by Mithras** [comment]
I'm not sure why this is closed but I'd like to add that the problem is present even when all subgraphs are up and running as expected. Please read my explanation here: https://github.com/apollographql/router/issues/1308#issuecomment-1172622949
