### ISSUE TITLE
Include the `operationName` in the OpenTelemetry span attributes

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#862]
As a follow-up to #836, it would be nice if the operation name which was provided by the client was attached as an OpenTelemetry span attribute.  This should be available (when provided) on the `requestContext`'s `operationName` property.  This will be an empty string (i.e., anonymous) when the operation name was not provided by the client.

**Comment by BrynCooke** [comment]
It's worth mentioning that on the Apollo Server side this instrumentation will likely be in the form of config of the HttpInstrumentation.
In the gateway we can either bake it in or use the same method to expose headers.

See [http-instrumentation](https://github.com/open-telemetry/opentelemetry-js/tree/main/packages/opentelemetry-instrumentation-http) `requestHook`

**Comment by BrynCooke** [comment]
Ahh, you are right.
We'll also have to look at trying to get this into graphql-instrumentation.

**Comment by abernix** [comment]
Closed by #942  (And client name/version should be a separate issue/PR?)
