### ISSUE TITLE
Unable to compile TypeScript after upgrade to apollo-server 3.0.0

### ISSUE THREAD

**Issue by mvanalphen** [apollographql/federation#877]
After upgrading to `apollo-server` 3.0.0 from version 2.25.2, using `@apollo/gateway` version 0.33.0, we are no longer able to compile the TypeScript for our GraphQL Gateway.

We've followed the Apollo Server migration guide and ensured all removed fields, like `subscriptions` and `playground` were removed from the `ApolloServer` instantiation. However, one issue remains, namely in the `gateway` property of the `ApolloServer`.

The error in question is:
```
TSError: ⨯ Unable to compile TypeScript:
src/main.ts:21:3 - error TS2322: Type 'ApolloGateway' is not assignable to type 'GatewayInterface'.
  The types returned by 'load(...)' are incompatible between these types.
    Type 'Promise<{ schema: GraphQLSchema; executor: <TContext>(requestContext: GraphQLRequestContextExecutionDidStart<TContext>) => Promise<...>; }>' is not assignable to type 'Promise<GraphQLServiceConfig>'.
      Type '{ schema: GraphQLSchema; executor: <TContext>(requestContext: GraphQLRequestContextExecutionDidStart<TContext>) => Promise<GraphQLExecutionResult>; }' is not assignable to type 'GraphQLServiceConfig'.
        Types of property 'executor' are incompatible.
          Type '<TContext>(requestContext: GraphQLRequestContextExecutionDidStart<TContext>) => Promise<GraphQLExecutionResult>' is not assignable to type 'GraphQLExecutor<Record<string, any>>'.
            Types of parameters 'requestContext' and 'requestContext' are incompatible.
              Type 'import(".../graphql-gateway/node_modules/apollo-server-core/node_modules/apollo-server-types/dist/index").GraphQLRequestContextExecutionDidStart<Record<string, any>>' is not assignable to type 'import(".../graphql-gateway/node_modules/apollo-server-types/dist/index").GraphQLRequestContextExecutionDidStart<Record<string, any>>'.
                Type 'GraphQLRequestContextExecutionDidStart<Record<string, any>>' is not assignable to type 'GraphQLRequestContext<Record<string, any>>'.
                  The types of 'overallCachePolicy.maxAge' are incompatible between these types.
                    Type 'number | undefined' is not assignable to type 'number'.
                      Type 'undefined' is not assignable to type 'number'.
```

We had a look at the Federation QuickStart documentation and didn't notice any differences in how the ApolloGateway and ApolloServer should be created. As such, we believe this may be an issue with the package itself.

We instantiate both as follows:

```
const gateway = new ApolloGateway({
  serviceList: [...environment.services],
  buildService: ({ url }) => {
    console.info(`Fetching from service ${url}`);
    return new IshAuthenticatedDataSource({ url });
  },
  // eslint-disable-next-line camelcase
  experimental_pollInterval: 60 * 1000 * 5
});

const server = new ApolloServer({
  gateway,
  context: ({ req }): ValueOrPromise<Context> => ({
    // Context headers go here
  }),
  introspection: environment.apollo.introspection
});
```

**Comment by glasser** [comment]
Do you have multiple copies of apollo-server-types installed (one directly
in node_modules and one under apollo-server-core)? Running `npm dedupe` may
help depending on the cause.

**Comment by glasser** [comment]
Or I mean, those errors show that you definitely do. So try npm dedup; if
that doesn't eliminate
node_modules/apollo-server-core/node_modules/apollo-server-types then can
you share your package-lock.json (privately with me at
***@***.*** if there are confidentiality concerns)?

**Comment by mvanalphen** [comment]
Well, that's embarrassing! Running `npm dedupe` indeed resolved the issue, despite our project using Yarn which apparently is supposed to [dedupe automatically](https://classic.yarnpkg.com/en/docs/cli/dedupe/) when you run `yarn install`. So not sure what happened there and how we even ended up with multiple copies.

Either way, that solves our issue and let's us start using Apollo Server 3. Thank you for the quick assist!

**Comment by glasser** [comment]
Great! Yeah, this is often a challenge with the npm model. I wish tsc had special-cased handling to provide a nice suggestion alongside errors that contain `node_modules/x` and `node_modules/y/node_modules/x`...
