### ISSUE TITLE
SchemaDirectiveVisitor undefined

### ISSUE THREAD

**Issue by EE1234EE** [apollographql/federation#886]
Hello Team,

I upgraded Apollo-Server from 2.25.2 to version 3.0.1 successfully. Following the migration guide and the documentation of Apollo Federation https://www.apollographql.com/docs/federation/subgraphs/#defining-custom-directives I should not get a problem. But I do, 

```
const { ApolloServer, SchemaDirectiveVisitor } = require("apollo-server-express");
const { KeycloakContext, KeycloakSchemaDirectives } = require('keycloak-connect-graphql');
...

const schema = buildFederatedSchema([ { typeDefs, resolvers } ], ); 

const directives = KeycloakSchemaDirectives;

SchemaDirectiveVisitor.visitSchemaDirectives(schema, directives); // <----- ERROR SchemaDirectiveVisitor = undefined

const server = new ApolloServer({
  schema,
  context: ({ req }) => {
    return {
      kauth: new KeycloakContext({ req })
    }
  }
});
```
Has anyone an idea? Am I at the correct GitHub-Repo or should I ask at Apollo-server-express or Apollo-Server? Or Am I not reading the documentation correctly?

At Version 2.25.2 of Apollo-Server the Error did not occur.

This is the index.js of an subgraph, this is not the gateway!

Error Message:
TypeError: Cannot read property 'visitSchemaDirectives' of undefined

NPM Dependencies:
"@apollo/federation": "^0.26.0",
    "@apollo/gateway": "^0.33.0",
    "@graphql-tools/load-files": "^6.3.2",
    "@graphql-tools/merge": "^6.2.14",
    "apollo-server-express": "^3.0.1",
    "axios": "^0.21.1",
    "axios-curlirize": "^1.4.0",
    "concurrently": "^6.2.0",
    "dotenv": "^10.0.0",
    "esm": "^3.2.25",
    "express": "^4.17.1",
    "express-session": "^1.17.2",
    "graphql": "^15.5.1",
    "graphql-playground-middleware-express": "^1.7.22",
    "graphql-scalars": "^1.10.0",
    "graphql-tools": "^7.0.5",
    "keycloak-connect": "^14.0.0",
    "keycloak-connect-graphql": "^0.7.0",
    "mongoose": "^5.13.3",
    "nanoid": "^3.1.23",
    "nodemon": "^2.0.12",
    "wait-on": "^5.3.0"

Thanks in advance and have nice day. :)

**Comment by glasser** [comment]
In Apollo Server 3, the packages no longer re-export dozens of symbols from an outdated version of `graphql-tools`; instead, you're welcome to choose your own version of `graphql-tools` and import it directly. See https://www.apollographql.com/docs/apollo-server/migration/#schemadirectives and https://www.apollographql.com/docs/apollo-server/migration/#exports-from-graphql-tools

**Comment by EE1234EE** [comment]
Ok, thank you very much.
