### ISSUE TITLE
chore: Update `harmonizer` to support `@tag`

### ISSUE THREAD

**Issue by abernix** [apollographql/federation#895]
## Requirements

The composition algorithm has been updated to support the `@tag` directive thanks to the work in https://github.com/apollographql/federation/pull/859 and follow-up issues.  That functionality is currently merged into the `release-federation-0.26.0` branch and published to the `rc` npm `dist-tag`.

In order for this behavior to be supported and offer the correct validations for `rover supergraph compose`, [the `harmonizer` crate](https://crates.io/crates/harmonizer) needs to be published after `release-federation-0.26.0` merges to `main` and a final `@apollo/federation` is published to `latest` in a non-prerelease form.

> Alternatively, a version should/could be published from the `release-federation-0.26.0` branch as a pre-release for validation purposes, if necessary, but **this issue should remain open until finalized.**

## Follow-up

After this is completed, `rover` needs to be updated to use the newly published `harmonizer` crate.

**Comment by abernix** [comment]
I understand this is published as [`harmonizer@0.27.0`](https://crates.io/crates/harmonizer/0.27.0).  Thanks, @trevor-scheer!

**Comment by trevor-scheer** [comment]
Via manual publish, and related commit: 6dde5e2
