### ISSUE TITLE
Apollo Gateway does not work with latest Apollo Server Version (3.*)

### ISSUE THREAD

**Issue by vany0114** [apollographql/federation#902]
Hi guys, not sure if you're aware of this issue.

I was migrating my gateway implementation to Apollo Server 3.* so started by migrating its graphql endpoints (all good there) but when I was migrating the gateway I realized that it throws an error at runtime:

```
UnhandledPromiseRejectionWarning: TypeError: Object.values(...).filter(...).flatMap is not a function
[start-service-accounts]     at Object.serverWillStart (C:\Users\vany0\OneDrive\Documentos\GitHub\apollo-client-cache-issue\federation-demo\services\accounts\node_modules\apollo-server-core\dist\plugin\cacheControl\index.js:40:22)
[start-service-accounts]     at Promise.all.plugins.map (C:\Users\vany0\OneDrive\Documentos\GitHub\apollo-client-cache-issue\federation-demo\services\accounts\node_modules\apollo-server-core\dist\ApolloServer.js:176:73)
[start-service-accounts]     at Array.map (<anonymous>)
[start-service-accounts]     at ApolloServer._start (C:\Users\vany0\OneDrive\Documentos\GitHub\apollo-client-cache-issue\federation-demo\services\accounts\node_modules\apollo-server-core\dist\ApolloServer.js:175:75)[start-service-accounts]     at ApolloServer.listen (C:\Users\vany0\OneDrive\Documentos\GitHub\apollo-client-cache-issue\federation-demo\services\accounts\node_modules\apollo-server\dist\index.js:56:20)
[start-service-accounts]     at Object.<anonymous> (C:\Users\vany0\OneDrive\Documentos\GitHub\apollo-client-cache-issue\federation-demo\services\accounts\index.js:38:8)
[start-service-accounts]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[start-service-accounts]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[start-service-accounts]     at Module.load (internal/modules/cjs/loader.js:653:32)
[start-service-accounts]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[start-service-accounts] (node:22488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
Basically, it is throwing the error [here](https://github.com/apollographql/federation/blob/4a4a099b2ea0e02736e43faf0eca548578cee580/federation-js/src/composition/compose.ts#L368)

I had a rough time trying to make it work w/o any luck, so I had to go undo the changes in the gateway and go back to use apollo-server `2.*` these are the dependencies I'm using in the gateway:

```
"@apollo/federation": "0.20.4",
"@apollo/gateway": "0.21.1",
"apollo-server": "^2.19.0",
```

So by using those dependencies I was able to run the gateway with its endpoints using apollo server `3.*`

Any ideas? 

You guys can replicate it by simply running the official [federation demo](https://github.com/apollographql/federation-demo)

**Comment by glasser** [comment]
What version of Node are you using?

**Comment by vany0114** [comment]
I'm using node 10.x

**Comment by glasser** [comment]
[Apollo Server 3 requires Node 12](https://www.apollographql.com/docs/apollo-server/migration/#bumped-dependencies). Node 10 is [no longer an LTS release](https://nodejs.org/en/about/releases/).

**Comment by vany0114** [comment]
Ok got it, but why the federated endpoints work fine even with node 10? I'm using Apollo Server 3 there as well

**Comment by glasser** [comment]
We stopped polyfilling some basic JS APIs and I guess the codepath that
doesn't work uses them and the codepath that does work doesn't use them.
