### ISSUE TITLE
feat(federation): Support `@deprecated` on input types

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/federation#912]
Currently our forked schema printer doesn't support this newer valid usage of `@deprecated` on input types in composition.

Related: https://github.com/graphql/graphql-js/pull/1560

**Comment by abernix** [comment]
Duplicate of https://github.com/apollographql/federation/issues/912.  This one was opened first, but there's slightly more information there so I'll close this one.  Thanks!

**Comment by abernix** [comment]
Sorry, meant duplicate of https://github.com/apollographql/federation/issues/635.
