### ISSUE TITLE
address TODO comments from vendored parser package

### ISSUE THREAD

**Issue by ashleygwilliams** [apollographql/federation#92]
as per https://github.com/apollographql/rust/blob/d0f1ff7eeba8a2867faffa65a3063d2cc442606d/graphql-parser/src/tokenizer.rs#L417

and https://github.com/apollographql/rust/blob/d0f1ff7eeba8a2867faffa65a3063d2cc442606d/graphql-parser/src/tokenizer.rs#L490

and https://github.com/apollographql/rust/blob/d0f1ff7eeba8a2867faffa65a3063d2cc442606d/graphql-parser/src/tokenizer.rs#L290

**Comment by Enrico2** [comment]
IIUC, most of what is under graphql-parser was forked from https://github.com/graphql-rust/graphql-parser and @queerviolet did some modifications. `tailhook` is the maintainer there as far as I can tell. I don't think we necessarily know what these TODOs mean at the moment.
It's possible that it's worth investigating whether or not these are actual issues we need to act on, but I suspect that we're going to trust our test suite for now, not do anything about these, and create new issues if/when we encounter a problem. 

(Fwiw it's possible we fixed these? Admittedly, I'm replying from my phone right now so I didn't check the diff to see how much we are diverged from the original copy of the code. Full disclosure I'm not personally too familiar with this crate, it was there from before I started contributing to the repo and didn't get a chance to explore it too deeply)

**Comment by ashleygwilliams** [comment]
@Enrico2 is there a reason that we are vendoring this and not contributing?

**Comment by Enrico2** [comment]
@ashleygwilliams No, I'm not sure, my guess would be just iteration speed? @queerviolet might know more details.

**Comment by pcmanus** [comment]
Closing as outdated (the code pointed at is not in use anymore).
