### ISSUE TITLE
Federation response different between Apollo 2 and Apollo 3 in error cases

### ISSUE THREAD

**Issue by arunthomas83** [apollographql/federation#974]
We were on apollo-server=2.19.1 and apollo/gateway=0.21.4 with Apollo2. As part of Apollo3 migration, we migrated our libraries to apollo-server=3.1.2 and apollo/gateway=0.36.0 library versions.

After started using the above versions for Apollo3, we noticed that the error response we receive from Gateway is different than from Apollo2. Even though the error structure from the implementing service is same across 2 and 3, the gateway response is different.

As per the Apollo support team, https://github.com/apollographql/federation/pull/159 was identified to be the cause of this discrepancy

Please find below the responses we received from Apollo2 and 3. As you can notice, `errors[1]` (below) in the response from Apollo Server 3 gateway (`INTERNAL_SERVER_ERROR`) is only present in Apollo 3 gateway response. On analysis, `INTERNAL_SERVER_ERROR` is not thrown from the implementing services, but from the Gateway itself.

Could you please check and do the needful so that the error response stays consistent between 2 and 3 as this will affect existing clients using the services.

### Response from **Apollo 2 Gateway**

```json
{
  "errors": [
    {
      "message": "MANDATORY_PARAM_MISSING",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "query": "{getByID(id:\"\"){firstName lastName emailAddress addresses{firstName id addressLine1}}}",
        "variables": {},
        "description": "Input Error : 1001_id",
        "traceId": "a4a05740-77f0-11eb-ab09-02a6d7f5cf9b"
      }
    }
  ],
  "data": null
}
```

### Response from **Apollo 3 Gateway**

```json
{
  "errors": [
    {
      "message": "MANDATORY_PARAM_MISSING",
      "extensions": {
        "code": "BAD_USER_INPUT",
        "description": "Input Error : 1001_id",
        "traceId": "a4a05740-77f0-11eb-ab09-02a6d7f5cf9b"
      }
    },
    {
      "message": "Cannot return null for non-nullable field Query.getByID.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
```

**Comment by MaxGoo** [comment]
I also ran into this and it's causing problems with how we display errors on our clients.

You can easily reproduce this by cloning the Apollo `federation-demo` and making some minor changes, here is a [codesandbox](https://codesandbox.io/s/apollo-gateway-issue-974-5x77q?file=/package.json) with those minor changes.

You'll have to open up two terminals in codesanbox and run `yarn start-services` in one and `yarn start-gateway` in the other.

**Comment by glasser** [comment]
I have a codesandbox linked from https://github.com/apollographql/federation/pull/159#issuecomment-901246314 that shows this issue.

**Comment by abernix** [comment]
Meant to close this issue with my above comment.  #982 takes over from here.  Thanks again for opening this originally!
