### ISSUE TITLE
Why does apollo gateway fire request to sub-service when there are no linking entities?

### ISSUE THREAD

**Issue by golfingal72** [apollographql/federation#989]
I am trying to reduce the requests to services when there are no entities to connect..  I there a way to stop this?
I see the gateway is firing requests when variables: {"representations":[]}

is there a way to stop this?

**Comment by abernix** [comment]
What version of `@apollo/gateway` are you running?  If you're running a version prior to `v0.25.1`, then I'd suggest upgrading to at least that version to make sure that you have [this improvement](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md#v0251).

If this is happening on v0.25.1 or after, it sounds like a bug and I'd ask for a small runnable reproduction of the problem so we could take a look.

**Comment by golfingal72** [comment]
Thanks... trying now...  I have:         "@apollo/gateway": "^0.21.4",

**Comment by golfingal72** [comment]
That did it... I don't know how I was so far behind!  Thanks so much

**Comment by abernix** [comment]
You bet! Glad this resolved it for you.
