### ISSUE TITLE
`printSupergraphSdl` and `printFederatedSchema` should support `@specifiedBy`

### ISSUE THREAD

**Issue by martijnwalraven** [apollographql/federation#994]
Both `printSupergraphSdl` and `printFederatedSchema` are forks of `printSchema` from `graphql-js`, and have not yet been updated to output `@specifiedBy` for scalar types (see [here](https://github.com/graphql/graphql-js/blob/da685ee1edcffe46bb6902ed48318f0f1905065e/src/utilities/printSchema.ts#L295-L301) for the corresponding code in `graphql-js`).

As far as I can see, this means we don't currently support `@specifiedBy` in subgraphs when using `@apollo/federation` (it won't show up under `{ _service { sdl } }`). And even though composition will keep `@specifiedBy` on type definitions, it won't show up in the printed supergraph SDL. (This means it may actually have worked for some people before the switch to supergraph SDL, when using local composition in the gateway with a non-Node server that does support `@specifiedBy` for subgraphs.)

**Comment by glasser** [comment]
If we can come up with a way for this to just involve running `printSchema` with appropriate arguments (perhaps with improvements to `printSchema`) that would be great!

**Comment by trevor-scheer** [comment]
@glasser our "forks" are doing quite a bit w.r.t. printing federation + other Apollo directives (@tag).

But in thinking along this path, it might be reasonable to call `printSchema`, re-parse it, visit and modify the AST, and call `print` on that. It wouldn't be trivial but it would likely remove the maintenance burden here. Just an idea / purely hypothetical, it's possible there are limitations I haven't imagined.
