### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Sytten** [apollographql/federation#999]
I could not find any changelog for federation, please add one so we don't have to diff the releases.

Thanks

**Comment by abernix** [comment]
Just so others know where to find them, they are in the package's directories in this monorepo and also published with the npm package:

| | | |
|-|-|-|
| `@apollo/gateway` | [`./gateway-js/CHANGELOG.md`](https://github.com/apollographql/federation/blob/HEAD/gateway-js/CHANGELOG.md) | [In the npm](https://unpkg.com/@apollo/gateway@latest/CHANGELOG.md) |
| `@apollo/federation` | [`./federation-js/CHANGELOG.md`](https://github.com/apollographql/federation/blob/HEAD/federation-js/CHANGELOG.md) | [In the npm](https://unpkg.com/@apollo/federation@latest/CHANGELOG.md) |


(These links point to `main` and `latest` packages)
